# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      gomod:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "*"
    commit-message:
      prefix: "[dep] "
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      gh:
        patterns:
          - "*"
    commit-message:
      prefix: "[ci] "
    labels:
      - "ci"
      - "dependencies"

  - package-ecosystem: gomod
    directories:
      - /docs/kubernetes
      - /docs/platypus2
      - /docs/terraform
    schedule:
      interval: monthly
    groups:
      gomod:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "*"
    commit-message:
      prefix: "[docs] "
    labels:
      - "doc"
      - "dependencies"
