# Copyright (c) Volvo Car Corporation
# SPDX-License-Identifier: Apache-2.0

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: lingon

dist: bin

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct

builds:

  #
  #  EXPLODE
  #
  # check results of yaml anchros
  # with https://yaml-online-parser.appspot.com/
  - &buildstep
    id: explode-linux
    binary: explode
    main: ./cmd/explode/cli.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # ensures mod timestamp to be the commit timestamp
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=https://proxy.golang.org,direct
    flags:
      - -trimpath
    ldflags:
      - >
        -s -w
        -extldflags "-static"
        -X main.version={{ .Version }}
        -X main.commit={{ .Commit }}
        -X main.date={{ .Date }}
        -X main.builtBy=goreleaser

  - <<: *buildstep
    id: explode-macos
    binary: explode
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  #
  #  KYGO
  #
  - <<: *buildstep
    id: kygo-linux
    binary: kygo
    main: ./cmd/kygo/cli.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - <<: *buildstep
    id: kygo-macos
    binary: kygo
    main: ./cmd/kygo/cli.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  #
  #  TERRAGEN
  #
  - <<: *buildstep
    id: terragen-linux
    binary: terragen
    main: ./cmd/terragen/cli.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - <<: *buildstep
    id: terragen-macos
    binary: terragen
    main: ./cmd/terragen/cli.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: explode
    format: tar.gz
    name_template: &artags "{{ .Binary }}_{{ .Os }}_{{ .Arch }}_{{ .ShortCommit }}"
    builds:
      - explode-linux
      - explode-macos
  - id: kygo
    format: tar.gz
    name_template: *artags
    builds:
      - kygo-linux
      - kygo-macos
  - id: terragen
    format: tar.gz
    name_template: *artags
    builds:
      - terragen-linux
      - terragen-macos

  - id: needed-for-homebrew
    builds:
      - explode-linux
      - explode-macos
      - kygo-linux
      - kygo-macos
      - terragen-linux
      - terragen-macos

checksum:
  name_template: 'checksums.txt'

sboms:
  - artifacts: archive
  - id: source # Two different sbom configurations need two different IDs
    artifacts: source

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^[Dd]ocs:'
      - '^[Tt]est:'
      - '^testdata:'

brews:
  - name: lingon
    ids:
      - needed-for-homebrew
    tap:
      owner: golingon
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/volvo-cars/lingon"
    description: |
      Lingon binaries:
      - explode is a command line tool to organize kubernetes manifests according to their kind. (YAML to YAML)
      - kygo is a command line tool to convert kubernetes YAML manifests to Go structs. (YAML to Go)
      - terragen generates Go code for Terraform providers.
    test: |
      system "#{bin}/explode -v"
      system "#{bin}/kygo -v"
      system "#{bin}/terragen -v"

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj