// Copyright (c) 2023 Volvo Car Corporation
// SPDX-License-Identifier: Apache-2.0

package terrajen

const fileExtension = ".go"

const HeaderComment = `CODE GENERATED BY github.com/volvo-cars/lingon. DO NOT EDIT.`

const (
	pkgTerraAlias = "terra"
	pkgTerra      = "github.com/volvo-cars/lingon/pkg/terra"
	pkgHCLAlias   = "hcl"
	pkgHCL        = "github.com/hashicorp/hcl/v2"
)

const (
	suffixArgs       = "Args"
	suffixAttributes = "Attributes"
	suffixState      = "State"
)

const (
	tagJSON     = "json"
	tagHCL      = "hcl"
	tagValidate = "validate"
)

const (
	idFuncInternalTraverse  = "InternalTraverse"
	idFuncReferenceAsString = "AsString"
	idFuncReferenceAsBool   = "AsBool"
	idFuncReferenceAsNumber = "AsNumber"
)

const (
	idFieldName  = "Name"
	idFieldArgs  = "Args"
	idFieldState = "state"

	idFuncType      = "Type"
	idFuncLocalName = "LocalName"
	idFuncState     = "State"
	idFuncStateMust = "StateMust"
)
