// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package nats

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var NS = &corev1.Namespace{
	ObjectMeta: metav1.ObjectMeta{Name: "nats"},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "v1",
		Kind:       "Namespace",
	},
}
