// Code generated by go-terriyaki. EDIT AS MUCH AS YOU LIKE.

package tekton

import (
	"github.com/volvo-cars/lingon/pkg/kubeutil"
	autoscalingv2 "k8s.io/api/autoscaling/v2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var PipelinesWebhookHPA = &autoscalingv2.HorizontalPodAutoscaler{
	ObjectMeta: metav1.ObjectMeta{
		Labels: kubeutil.MergeLabels(
			map[string]string{kubeutil.AppLabelName: WebhookName},
			labelsWebhook,
			labelsVersion,
		),
		Name:      WebhookFullName,
		Namespace: PipelinesNS.Name,
	},
	Spec: autoscalingv2.HorizontalPodAutoscalerSpec{
		MaxReplicas: int32(5),
		Metrics: []autoscalingv2.MetricSpec{
			{
				Resource: &autoscalingv2.ResourceMetricSource{
					Name: corev1.ResourceCPU,
					Target: autoscalingv2.MetricTarget{
						AverageUtilization: P(int32(100)),
						Type:               autoscalingv2.UtilizationMetricType,
					},
				},
				Type: autoscalingv2.ResourceMetricSourceType,
			},
		},
		MinReplicas: P(int32(1)),
		ScaleTargetRef: autoscalingv2.CrossVersionObjectReference{
			APIVersion: PipelinesWebhookDeploy.APIVersion,
			Kind:       PipelinesWebhookDeploy.Kind,
			Name:       PipelinesWebhookDeploy.Name,
		},
	},
	TypeMeta: kubeutil.TypeHorizontalPodAutoscalerV2,
}
