apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: team-onboarding-auth
spec:
  parameters:
    objects: |
      - objectName: "xxx-gh-token"
        secretPath: "team-onboarding-kv/data/github-xxx-bot"
        secretKey: "token"
      - objectName: "xxx-gh-username"
        secretPath: "team-onboarding-kv/data/github-xxx-bot"
        secretKey: "username"
      - objectName: "harbor-username"
        secretPath: "team-onboarding-kv/data/harbor"
        secretKey: "username"
      - objectName: "harbor-password"
        secretPath: "team-onboarding-kv/data/harbor"
        secretKey: "password"
      - objectName: "sendgrid-api-key"
        secretPath: "team-onboarding-kv/data/sendgrid-api-key"
        secretKey: "token"
      - objectName: "key-id"
        secretPath: "team-onboarding-kv/data/lakefs-xxx-admin"
        secretKey: "access-key-id"
      - objectName: "secret-key"
        secretPath: "team-onboarding-kv/data/lakefs-xxx-admin"
        secretKey: "secret-access-key"
      - objectName: "abk-vcc-test-xxx-xxx-gh-dev-token"
        secretPath: "team-onboarding-kv/data/abk-vcc-test-xxx-bot"
        secretKey: "token"
      - objectName: "abk-vcc-test-xxx-gh-dev-username"
        secretPath: "team-onboarding-kv/data/abk-vcc-test-xxx-bot"
        secretKey: "username"
      - objectName: "scim-auth-token"
        secretPath: "team-onboarding-kv/data/scim-token"
        secretKey: "token"
      - objectName: "team-az-group-management-prod"
        secretPath: "team-onboarding-kv/data/team-az-group-management-prod"
        secretKey: "client-secret"
      - objectName: "team-az-group-management-qa"
        secretPath: "team-onboarding-kv/data/team-az-group-management-qa"
        secretKey: "client-secret"
    roleName: team-onboarding-policy-read
    vaultAddress: https://vault.secretstore.company.com
  provider: vault
  secretObjects:
  - data:
    - key: token
      objectName: xxx-gh-token
    - key: username
      objectName: xxx-gh-username
    secretName: github-auth
    type: Opaque
  - data:
    - key: token
      objectName: abk-vcc-test-xxx-xxx-gh-dev-token
    - key: username
      objectName: abk-vcc-test-xxx-gh-dev-username
    secretName: github-abk-vcc-test-auth
    type: Opaque
  - data:
    - key: token
      objectName: scim-auth-token
    secretName: scim-auth
    type: Opaque
  - data:
    - key: username
      objectName: harbor-username
    - key: password
      objectName: harbor-password
    secretName: harbor-auth
    type: Opaque
  - data:
    - key: access-key-id
      objectName: key-id
    - key: secret-access-key
      objectName: secret-key
    secretName: lakefs-auth
    type: Opaque
  - data:
    - key: token
      objectName: sendgrid-api-key
    secretName: sendgrid-api-key
    type: Opaque
  - data:
    - key: client-secret
      objectName: team-az-group-management-prod
    secretName: team-az-group-management-prod
    type: Opaque
  - data:
    - key: client-secret
      objectName: team-az-group-management-qa
    secretName: team-az-group-management-qa
    type: Opaque
