// CODE GENERATED BY github.com/volvo-cars/lingon. DO NOT EDIT.

package local

import "github.com/volvo-cars/lingon/pkg/terra"

func NewDataSensitiveFile(
	name string,
	args DataSensitiveFileArgs,
) *DataSensitiveFile {
	return &DataSensitiveFile{
		Args: args,
		Name: name,
	}
}

var _ terra.DataResource = (*DataSensitiveFile)(nil)

type DataSensitiveFile struct {
	Name string
	Args DataSensitiveFileArgs
}

func (sf *DataSensitiveFile) DataSource() string {
	return "local_sensitive_file"
}

func (sf *DataSensitiveFile) LocalName() string {
	return sf.Name
}

func (sf *DataSensitiveFile) Configuration() interface{} {
	return sf.Args
}

func (sf *DataSensitiveFile) Attributes() dataSensitiveFileAttributes {
	return dataSensitiveFileAttributes{name: sf.Name}
}

type DataSensitiveFileArgs struct {
	// Filename: string, required
	Filename terra.StringValue `hcl:"filename,attr" validate:"required"`
}
type dataSensitiveFileAttributes struct {
	name string
}

func (sf dataSensitiveFileAttributes) Content() terra.StringValue {
	return terra.Reference(
		"data",
		"local_sensitive_file",
		sf.name,
		"content",
	).AsString()
}

func (sf dataSensitiveFileAttributes) ContentBase64() terra.StringValue {
	return terra.Reference(
		"data",
		"local_sensitive_file",
		sf.name,
		"content_base64",
	).AsString()
}

func (sf dataSensitiveFileAttributes) ContentBase64Sha256() terra.StringValue {
	return terra.Reference(
		"data",
		"local_sensitive_file",
		sf.name,
		"content_base64sha256",
	).AsString()
}

func (sf dataSensitiveFileAttributes) ContentBase64Sha512() terra.StringValue {
	return terra.Reference(
		"data",
		"local_sensitive_file",
		sf.name,
		"content_base64sha512",
	).AsString()
}

func (sf dataSensitiveFileAttributes) ContentMd5() terra.StringValue {
	return terra.Reference(
		"data",
		"local_sensitive_file",
		sf.name,
		"content_md5",
	).AsString()
}

func (sf dataSensitiveFileAttributes) ContentSha1() terra.StringValue {
	return terra.Reference(
		"data",
		"local_sensitive_file",
		sf.name,
		"content_sha1",
	).AsString()
}

func (sf dataSensitiveFileAttributes) ContentSha256() terra.StringValue {
	return terra.Reference(
		"data",
		"local_sensitive_file",
		sf.name,
		"content_sha256",
	).AsString()
}

func (sf dataSensitiveFileAttributes) ContentSha512() terra.StringValue {
	return terra.Reference(
		"data",
		"local_sensitive_file",
		sf.name,
		"content_sha512",
	).AsString()
}

func (sf dataSensitiveFileAttributes) Filename() terra.StringValue {
	return terra.Reference(
		"data",
		"local_sensitive_file",
		sf.name,
		"filename",
	).AsString()
}

func (sf dataSensitiveFileAttributes) Id() terra.StringValue {
	return terra.Reference(
		"data",
		"local_sensitive_file",
		sf.name,
		"id",
	).AsString()
}
