// Copyright (c) 2023 Volvo Car Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package vmk8s

import (
	_ "embed"

	ku "github.com/volvo-cars/lingon/pkg/kubeutil"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func LoadDashAsCM(
	filename, dashJSON string,
	o metav1.ObjectMeta,
) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		TypeMeta:   ku.TypeConfigMapV1,
		ObjectMeta: PatchDashLabels(o),
		Data: map[string]string{
			filename: dashJSON,
		},
	}
}

var (
	//go:embed dashboards/backupmanager.json
	backupmanagerDash        string
	DashboardBackupManagerCM = LoadDashAsCM(
		"backupmanager.json",
		backupmanagerDash,
		Graf.ObjectMetaNameSuffix("backup-manager-dash"),
	)

	//go:embed dashboards/k8s-views-global.json
	k8sGlobalDash        string
	DashboardK8SGlobalCM = LoadDashAsCM(
		"k8s-views-global.json",
		k8sGlobalDash,
		Graf.ObjectMetaNameSuffix("k8s-global"),
	)

	//go:embed dashboards/k8s-views-namespaces.json
	k8sNSDash                string
	DashboardK8SNamespacesCM = LoadDashAsCM(
		"k8s-views-namespaces.json",
		k8sNSDash,
		Graf.ObjectMetaNameSuffix("k8s-namespaces"),
	)

	//go:embed dashboards/k8s-views-pods.json
	k8sPodsDash        string
	DashboardK8SPodsCM = LoadDashAsCM(
		"k8s-views-pods.json",
		k8sPodsDash,
		Graf.ObjectMetaNameSuffix("k8s-pods"),
	)

	//go:embed dashboards/vm-operator.json
	vmOperatorDash      string
	DashboardVMOperator = LoadDashAsCM(
		"vm-operator.json",
		vmOperatorDash,
		Graf.ObjectMetaNameSuffix("vm-operator"),
	)

	//go:embed dashboards/grafana-overview.json
	grafanaOverviewDash   string
	GrafanaOverviewDashCM = LoadDashAsCM(
		"grafana-overview.json",
		grafanaOverviewDash,
		Graf.ObjectMetaNameSuffix("dash-overview"),
	)

	//go:embed dashboards/k8s-system-coredns.json
	corednsDash string

	CoreDNSDashboardCM = LoadDashAsCM(
		"k8s-coredns.json",
		corednsDash,
		CDNS.ObjectMetaNameSuffix("dash"),
	)

	// go:embed dashboards/vmagent.json
	vmAgentDash      string
	DashboardAgentCM = LoadDashAsCM(
		"vmagent.json",
		vmAgentDash,
		Graf.ObjectMetaNameSuffix("vmagent"),
	)

	//go:embed dashboards/alertmanager-overview.json
	alertManagerOverviewDash   string
	AlertManagerOverviewDashCM = LoadDashAsCM(
		"alertmanager-overview.json",
		alertManagerOverviewDash,
		AM.ObjectMetaNameSuffix("vmalert-overview-dash"),
	)

	//go:embed dashboards/vmalert.json
	alertManagerDash        string
	AlertManagerDashboardCM = LoadDashAsCM(
		"vmalert.json",
		alertManagerDash,
		AM.ObjectMetaNameSuffix("vmalert-dash"),
	)

	//go:embed dashboards/victoriametrics.json
	victoriaMetricsDash        string
	DashboardVictoriaMetricsCM = LoadDashAsCM(
		"victoriametrics.json",
		victoriaMetricsDash,
		Single.ObjectMetaNameSuffix("vmsingle-dash"),
	)
)
