// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package grafana

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func DashboardsDefaultCm(opts KubeOpts) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "ConfigMap",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "grafana-dashboards-default",
			Namespace: opts.Namespace,
			Labels:    opts.CommonLabels,
		},
		Data: map[string]string{},
	}
}
