// Code generated by go-kart. EDIT AS MUCH AS YOU LIKE.

package webhook

import (
	"github.com/volvo-cars/lingon/pkg/kubeutil"
	arv1 "k8s.io/api/admissionregistration/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var ExternalsecretValidateValidatingWH = &arv1.ValidatingWebhookConfiguration{
	TypeMeta: kubeutil.TypeValidatingWebhookConfigurationV1,
	ObjectMeta: metav1.ObjectMeta{
		Labels: map[string]string{"external-secrets.io/component": "webhook"},
		Name:   "externalsecret-validate",
	},

	Webhooks: []arv1.ValidatingWebhook{
		{
			AdmissionReviewVersions: []string{"v1", "v1beta1"},
			ClientConfig: arv1.WebhookClientConfig{
				Service: &arv1.ServiceReference{
					Name:      "external-secrets-webhook",
					Namespace: "external-secrets",
					Path:      P("/validate-external-secrets-io-v1beta1-externalsecret"),
				},
			},
			FailurePolicy: P(arv1.FailurePolicyType("Fail")),
			Name:          "validate.externalsecret.external-secrets.io",
			Rules: []arv1.RuleWithOperations{
				{
					Operations: []arv1.OperationType{
						arv1.Create,
						arv1.Update,
						arv1.Delete,
					},
					Rule: arv1.Rule{
						APIGroups:   []string{"external-secrets.io"},
						APIVersions: []string{"v1beta1"},
						Resources:   []string{"externalsecrets"},
						Scope:       P(arv1.NamespacedScope),
					},
				},
			},
			SideEffects:    P(arv1.SideEffectClassNone),
			TimeoutSeconds: P(int32(5)),
		},
	},
}
