// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package vmcrd

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var VmprobesOperatorVictoriametricsComCRD = &apiextensionsv1.CustomResourceDefinition{
	ObjectMeta: metav1.ObjectMeta{
		Annotations: map[string]string{"controller-gen.kubebuilder.io/version": "v0.10.0"},
		Name:        "vmprobes.operator.victoriametrics.com",
	},
	Spec: apiextensionsv1.CustomResourceDefinitionSpec{
		Group: "operator.victoriametrics.com",
		Names: apiextensionsv1.CustomResourceDefinitionNames{
			Kind:     "VMProbe",
			ListKind: "VMProbeList",
			Plural:   "vmprobes",
			Singular: "vmprobe",
		},
		Scope: apiextensionsv1.ResourceScope("Namespaced"),
		Versions: []apiextensionsv1.CustomResourceDefinitionVersion{apiextensionsv1.CustomResourceDefinitionVersion{
			Name: "v1beta1",
			Schema: &apiextensionsv1.CustomResourceValidation{OpenAPIV3Schema: &apiextensionsv1.JSONSchemaProps{
				Description: "VMProbe defines a probe for targets, that will be executed with prober, like blackbox exporter. It helps to monitor reachability of target with various checks.",
				Properties: map[string]apiextensionsv1.JSONSchemaProps{
					"apiVersion": apiextensionsv1.JSONSchemaProps{
						Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
						Type:        "string",
					},
					"kind": apiextensionsv1.JSONSchemaProps{
						Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
						Type:        "string",
					},
					"metadata": apiextensionsv1.JSONSchemaProps{Type: "object"},
					"spec": apiextensionsv1.JSONSchemaProps{
						Description: "VMProbeSpec contains specification parameters for a Probe.",
						Properties: map[string]apiextensionsv1.JSONSchemaProps{
							"authorization": apiextensionsv1.JSONSchemaProps{
								Description: "Authorization with http header Authorization",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"credentials": apiextensionsv1.JSONSchemaProps{
										Description: "Reference to the secret with value for authorization",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"key": apiextensionsv1.JSONSchemaProps{
												Description: "The key of the secret to select from.  Must be a valid secret key.",
												Type:        "string",
											},
											"name": apiextensionsv1.JSONSchemaProps{
												Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
												Type:        "string",
											},
											"optional": apiextensionsv1.JSONSchemaProps{
												Description: "Specify whether the Secret or its key must be defined",
												Type:        "boolean",
											},
										},
										Required: []string{"key"},
										Type:     "object",
										XMapType: P("atomic"),
									},
									"credentialsFile": apiextensionsv1.JSONSchemaProps{
										Description: "File with value for authorization",
										Type:        "string",
									},
									"type": apiextensionsv1.JSONSchemaProps{
										Description: "Type of authorization, default to bearer",
										Type:        "string",
									},
								},
								Type: "object",
							},
							"basicAuth": apiextensionsv1.JSONSchemaProps{
								Description: "BasicAuth allow an endpoint to authenticate over basic authentication More info: https://prometheus.io/docs/operating/configuration/#endpoints",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"password": apiextensionsv1.JSONSchemaProps{
										Description: "The secret in the service scrape namespace that contains the password for authentication. It must be at them same namespace as CRD",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"key": apiextensionsv1.JSONSchemaProps{
												Description: "The key of the secret to select from.  Must be a valid secret key.",
												Type:        "string",
											},
											"name": apiextensionsv1.JSONSchemaProps{
												Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
												Type:        "string",
											},
											"optional": apiextensionsv1.JSONSchemaProps{
												Description: "Specify whether the Secret or its key must be defined",
												Type:        "boolean",
											},
										},
										Required: []string{"key"},
										Type:     "object",
										XMapType: P("atomic"),
									},
									"password_file": apiextensionsv1.JSONSchemaProps{
										Description: "PasswordFile defines path to password file at disk",
										Type:        "string",
									},
									"username": apiextensionsv1.JSONSchemaProps{
										Description: "The secret in the service scrape namespace that contains the username for authentication. It must be at them same namespace as CRD",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"key": apiextensionsv1.JSONSchemaProps{
												Description: "The key of the secret to select from.  Must be a valid secret key.",
												Type:        "string",
											},
											"name": apiextensionsv1.JSONSchemaProps{
												Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
												Type:        "string",
											},
											"optional": apiextensionsv1.JSONSchemaProps{
												Description: "Specify whether the Secret or its key must be defined",
												Type:        "boolean",
											},
										},
										Required: []string{"key"},
										Type:     "object",
										XMapType: P("atomic"),
									},
								},
								Type: "object",
							},
							"bearerTokenFile": apiextensionsv1.JSONSchemaProps{
								Description: "File to read bearer token for scraping targets.",
								Type:        "string",
							},
							"bearerTokenSecret": apiextensionsv1.JSONSchemaProps{
								Description: "Secret to mount to read bearer token for scraping targets. The secret needs to be in the same namespace as the service scrape and accessible by the victoria-metrics operator.",
								Nullable:    true,
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"key": apiextensionsv1.JSONSchemaProps{
										Description: "The key of the secret to select from.  Must be a valid secret key.",
										Type:        "string",
									},
									"name": apiextensionsv1.JSONSchemaProps{
										Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
										Type:        "string",
									},
									"optional": apiextensionsv1.JSONSchemaProps{
										Description: "Specify whether the Secret or its key must be defined",
										Type:        "boolean",
									},
								},
								Required: []string{"key"},
								Type:     "object",
								XMapType: P("atomic"),
							},
							"follow_redirects": apiextensionsv1.JSONSchemaProps{
								Description: "FollowRedirects controls redirects for scraping.",
								Type:        "boolean",
							},
							"interval": apiextensionsv1.JSONSchemaProps{
								Description: "Interval at which targets are probed using the configured prober. If not specified Prometheus' global scrape interval is used.",
								Type:        "string",
							},
							"jobName": apiextensionsv1.JSONSchemaProps{
								Description: "The job name assigned to scraped metrics by default.",
								Type:        "string",
							},
							"module": apiextensionsv1.JSONSchemaProps{
								Description: "The module to use for probing specifying how to probe the target. Example module configuring in the blackbox exporter: https://github.com/prometheus/blackbox_exporter/blob/master/example.yml",
								Type:        "string",
							},
							"oauth2": apiextensionsv1.JSONSchemaProps{
								Description: "OAuth2 defines auth configuration",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"client_id": apiextensionsv1.JSONSchemaProps{
										Description: "The secret or configmap containing the OAuth2 client id",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"configMap": apiextensionsv1.JSONSchemaProps{
												Description: "ConfigMap containing data to use for the targets.",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"key": apiextensionsv1.JSONSchemaProps{
														Description: "The key to select.",
														Type:        "string",
													},
													"name": apiextensionsv1.JSONSchemaProps{
														Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
														Type:        "string",
													},
													"optional": apiextensionsv1.JSONSchemaProps{
														Description: "Specify whether the ConfigMap or its key must be defined",
														Type:        "boolean",
													},
												},
												Required: []string{"key"},
												Type:     "object",
												XMapType: P("atomic"),
											},
											"secret": apiextensionsv1.JSONSchemaProps{
												Description: "Secret containing data to use for the targets.",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"key": apiextensionsv1.JSONSchemaProps{
														Description: "The key of the secret to select from.  Must be a valid secret key.",
														Type:        "string",
													},
													"name": apiextensionsv1.JSONSchemaProps{
														Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
														Type:        "string",
													},
													"optional": apiextensionsv1.JSONSchemaProps{
														Description: "Specify whether the Secret or its key must be defined",
														Type:        "boolean",
													},
												},
												Required: []string{"key"},
												Type:     "object",
												XMapType: P("atomic"),
											},
										},
										Type: "object",
									},
									"client_secret": apiextensionsv1.JSONSchemaProps{
										Description: "The secret containing the OAuth2 client secret",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"key": apiextensionsv1.JSONSchemaProps{
												Description: "The key of the secret to select from.  Must be a valid secret key.",
												Type:        "string",
											},
											"name": apiextensionsv1.JSONSchemaProps{
												Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
												Type:        "string",
											},
											"optional": apiextensionsv1.JSONSchemaProps{
												Description: "Specify whether the Secret or its key must be defined",
												Type:        "boolean",
											},
										},
										Required: []string{"key"},
										Type:     "object",
										XMapType: P("atomic"),
									},
									"client_secret_file": apiextensionsv1.JSONSchemaProps{
										Description: "ClientSecretFile defines path for client secret file.",
										Type:        "string",
									},
									"endpoint_params": apiextensionsv1.JSONSchemaProps{
										AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
											Allows: true,
											Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
										},
										Description: "Parameters to append to the token URL",
										Type:        "object",
									},
									"scopes": apiextensionsv1.JSONSchemaProps{
										Description: "OAuth2 scopes used for the token request",
										Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
										Type:        "array",
									},
									"token_url": apiextensionsv1.JSONSchemaProps{
										Description: "The URL to fetch the token from",
										MinLength:   P(int64(1)),
										Type:        "string",
									},
								},
								Required: []string{"client_id", "token_url"},
								Type:     "object",
							},
							"params": apiextensionsv1.JSONSchemaProps{
								AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
									Allows: true,
									Schema: &apiextensionsv1.JSONSchemaProps{
										Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
										Type:  "array",
									},
								},
								Description: "Optional HTTP URL parameters",
								Type:        "object",
							},
							"sampleLimit": apiextensionsv1.JSONSchemaProps{
								Description: "SampleLimit defines per-scrape limit on number of scraped samples that will be accepted.",
								Format:      "int64",
								Type:        "integer",
							},
							"scrapeTimeout": apiextensionsv1.JSONSchemaProps{
								Description: "Timeout for scraping metrics from the Prometheus exporter.",
								Type:        "string",
							},
							"scrape_interval": apiextensionsv1.JSONSchemaProps{
								Description: "ScrapeInterval is the same as Interval and has priority over it. one of scrape_interval or interval can be used",
								Type:        "string",
							},
							"targets": apiextensionsv1.JSONSchemaProps{
								Description: "Targets defines a set of static and/or dynamically discovered targets to be probed using the prober.",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"ingress": apiextensionsv1.JSONSchemaProps{
										Description: "Ingress defines the set of dynamically discovered ingress objects which hosts are considered for probing.",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"namespaceSelector": apiextensionsv1.JSONSchemaProps{
												Description: "Select Ingress objects by namespace.",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"any": apiextensionsv1.JSONSchemaProps{
														Description: "Boolean describing whether all namespaces are selected in contrast to a list restricting them.",
														Type:        "boolean",
													},
													"matchNames": apiextensionsv1.JSONSchemaProps{
														Description: "List of namespace names.",
														Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
														Type:        "array",
													},
												},
												Type: "object",
											},
											"relabelingConfigs": apiextensionsv1.JSONSchemaProps{
												Description: "RelabelConfigs to apply to samples before ingestion. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config",
												Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
													Description: "RelabelConfig allows dynamic rewriting of the label set, being applied to samples before ingestion. It defines `<metric_relabel_configs>`-section of configuration. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"action": apiextensionsv1.JSONSchemaProps{
															Description: "Action to perform based on regex matching. Default is 'replace'",
															Type:        "string",
														},
														"if": apiextensionsv1.JSONSchemaProps{
															Description: "If represents metricsQL match expression: '{__name__=~\"foo_.*\"}'",
															Type:        "string",
														},
														"labels": apiextensionsv1.JSONSchemaProps{
															AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
																Allows: true,
																Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
															},
															Description: "Labels is used together with Match for `action: graphite`",
															Type:        "object",
														},
														"match": apiextensionsv1.JSONSchemaProps{
															Description: "Match is used together with Labels for `action: graphite`",
															Type:        "string",
														},
														"modulus": apiextensionsv1.JSONSchemaProps{
															Description: "Modulus to take of the hash of the source label values.",
															Format:      "int64",
															Type:        "integer",
														},
														"regex": apiextensionsv1.JSONSchemaProps{
															Description: "Regular expression against which the extracted value is matched. Default is '(.*)'",
															Type:        "string",
														},
														"replacement": apiextensionsv1.JSONSchemaProps{
															Description: "Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available. Default is '$1'",
															Type:        "string",
														},
														"separator": apiextensionsv1.JSONSchemaProps{
															Description: "Separator placed between concatenated source label values. default is ';'.",
															Type:        "string",
														},
														"sourceLabels": apiextensionsv1.JSONSchemaProps{
															Description: "The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions.",
															Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
															Type:        "array",
														},
														"source_labels": apiextensionsv1.JSONSchemaProps{
															Description: "UnderScoreSourceLabels - additional form of source labels source_labels for compatibility with original relabel config. if set  both sourceLabels and source_labels, sourceLabels has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
															Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
															Type:        "array",
														},
														"targetLabel": apiextensionsv1.JSONSchemaProps{
															Description: "Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available.",
															Type:        "string",
														},
														"target_label": apiextensionsv1.JSONSchemaProps{
															Description: "UnderScoreTargetLabel - additional form of target label - target_label for compatibility with original relabel config. if set  both targetLabel and target_label, targetLabel has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
															Type:        "string",
														},
													},
													Type: "object",
												}},
												Type: "array",
											},
											"selector": apiextensionsv1.JSONSchemaProps{
												Description: "Select Ingress objects by labels.",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"matchExpressions": apiextensionsv1.JSONSchemaProps{
														Description: "matchExpressions is a list of label selector requirements. The requirements are ANDed.",
														Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
															Description: "A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"key": apiextensionsv1.JSONSchemaProps{
																	Description: "key is the label key that the selector applies to.",
																	Type:        "string",
																},
																"operator": apiextensionsv1.JSONSchemaProps{
																	Description: "operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.",
																	Type:        "string",
																},
																"values": apiextensionsv1.JSONSchemaProps{
																	Description: "values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.",
																	Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
																	Type:        "array",
																},
															},
															Required: []string{"key", "operator"},
															Type:     "object",
														}},
														Type: "array",
													},
													"matchLabels": apiextensionsv1.JSONSchemaProps{
														AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
															Allows: true,
															Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
														},
														Description: "matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed.",
														Type:        "object",
													},
												},
												Type:     "object",
												XMapType: P("atomic"),
											},
										},
										Type: "object",
									},
									"staticConfig": apiextensionsv1.JSONSchemaProps{
										Description: "StaticConfig defines static targets which are considers for probing. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config.",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"labels": apiextensionsv1.JSONSchemaProps{
												AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
													Allows: true,
													Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
												},
												Description: "Labels assigned to all metrics scraped from the targets.",
												Type:        "object",
											},
											"relabelingConfigs": apiextensionsv1.JSONSchemaProps{
												Description: "More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config",
												Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
													Description: "RelabelConfig allows dynamic rewriting of the label set, being applied to samples before ingestion. It defines `<metric_relabel_configs>`-section of configuration. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"action": apiextensionsv1.JSONSchemaProps{
															Description: "Action to perform based on regex matching. Default is 'replace'",
															Type:        "string",
														},
														"if": apiextensionsv1.JSONSchemaProps{
															Description: "If represents metricsQL match expression: '{__name__=~\"foo_.*\"}'",
															Type:        "string",
														},
														"labels": apiextensionsv1.JSONSchemaProps{
															AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
																Allows: true,
																Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
															},
															Description: "Labels is used together with Match for `action: graphite`",
															Type:        "object",
														},
														"match": apiextensionsv1.JSONSchemaProps{
															Description: "Match is used together with Labels for `action: graphite`",
															Type:        "string",
														},
														"modulus": apiextensionsv1.JSONSchemaProps{
															Description: "Modulus to take of the hash of the source label values.",
															Format:      "int64",
															Type:        "integer",
														},
														"regex": apiextensionsv1.JSONSchemaProps{
															Description: "Regular expression against which the extracted value is matched. Default is '(.*)'",
															Type:        "string",
														},
														"replacement": apiextensionsv1.JSONSchemaProps{
															Description: "Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available. Default is '$1'",
															Type:        "string",
														},
														"separator": apiextensionsv1.JSONSchemaProps{
															Description: "Separator placed between concatenated source label values. default is ';'.",
															Type:        "string",
														},
														"sourceLabels": apiextensionsv1.JSONSchemaProps{
															Description: "The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions.",
															Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
															Type:        "array",
														},
														"source_labels": apiextensionsv1.JSONSchemaProps{
															Description: "UnderScoreSourceLabels - additional form of source labels source_labels for compatibility with original relabel config. if set  both sourceLabels and source_labels, sourceLabels has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
															Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
															Type:        "array",
														},
														"targetLabel": apiextensionsv1.JSONSchemaProps{
															Description: "Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available.",
															Type:        "string",
														},
														"target_label": apiextensionsv1.JSONSchemaProps{
															Description: "UnderScoreTargetLabel - additional form of target label - target_label for compatibility with original relabel config. if set  both targetLabel and target_label, targetLabel has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
															Type:        "string",
														},
													},
													Type: "object",
												}},
												Type: "array",
											},
											"targets": apiextensionsv1.JSONSchemaProps{
												Description: "Targets is a list of URLs to probe using the configured prober.",
												Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
												Type:        "array",
											},
										},
										Required: []string{"targets"},
										Type:     "object",
									},
								},
								Type: "object",
							},
							"tlsConfig": apiextensionsv1.JSONSchemaProps{
								Description: "TLSConfig configuration to use when scraping the endpoint",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"ca": apiextensionsv1.JSONSchemaProps{
										Description: "Stuct containing the CA cert to use for the targets.",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"configMap": apiextensionsv1.JSONSchemaProps{
												Description: "ConfigMap containing data to use for the targets.",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"key": apiextensionsv1.JSONSchemaProps{
														Description: "The key to select.",
														Type:        "string",
													},
													"name": apiextensionsv1.JSONSchemaProps{
														Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
														Type:        "string",
													},
													"optional": apiextensionsv1.JSONSchemaProps{
														Description: "Specify whether the ConfigMap or its key must be defined",
														Type:        "boolean",
													},
												},
												Required: []string{"key"},
												Type:     "object",
												XMapType: P("atomic"),
											},
											"secret": apiextensionsv1.JSONSchemaProps{
												Description: "Secret containing data to use for the targets.",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"key": apiextensionsv1.JSONSchemaProps{
														Description: "The key of the secret to select from.  Must be a valid secret key.",
														Type:        "string",
													},
													"name": apiextensionsv1.JSONSchemaProps{
														Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
														Type:        "string",
													},
													"optional": apiextensionsv1.JSONSchemaProps{
														Description: "Specify whether the Secret or its key must be defined",
														Type:        "boolean",
													},
												},
												Required: []string{"key"},
												Type:     "object",
												XMapType: P("atomic"),
											},
										},
										Type: "object",
									},
									"caFile": apiextensionsv1.JSONSchemaProps{
										Description: "Path to the CA cert in the container to use for the targets.",
										Type:        "string",
									},
									"cert": apiextensionsv1.JSONSchemaProps{
										Description: "Struct containing the client cert file for the targets.",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"configMap": apiextensionsv1.JSONSchemaProps{
												Description: "ConfigMap containing data to use for the targets.",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"key": apiextensionsv1.JSONSchemaProps{
														Description: "The key to select.",
														Type:        "string",
													},
													"name": apiextensionsv1.JSONSchemaProps{
														Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
														Type:        "string",
													},
													"optional": apiextensionsv1.JSONSchemaProps{
														Description: "Specify whether the ConfigMap or its key must be defined",
														Type:        "boolean",
													},
												},
												Required: []string{"key"},
												Type:     "object",
												XMapType: P("atomic"),
											},
											"secret": apiextensionsv1.JSONSchemaProps{
												Description: "Secret containing data to use for the targets.",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"key": apiextensionsv1.JSONSchemaProps{
														Description: "The key of the secret to select from.  Must be a valid secret key.",
														Type:        "string",
													},
													"name": apiextensionsv1.JSONSchemaProps{
														Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
														Type:        "string",
													},
													"optional": apiextensionsv1.JSONSchemaProps{
														Description: "Specify whether the Secret or its key must be defined",
														Type:        "boolean",
													},
												},
												Required: []string{"key"},
												Type:     "object",
												XMapType: P("atomic"),
											},
										},
										Type: "object",
									},
									"certFile": apiextensionsv1.JSONSchemaProps{
										Description: "Path to the client cert file in the container for the targets.",
										Type:        "string",
									},
									"insecureSkipVerify": apiextensionsv1.JSONSchemaProps{
										Description: "Disable target certificate validation.",
										Type:        "boolean",
									},
									"keyFile": apiextensionsv1.JSONSchemaProps{
										Description: "Path to the client key file in the container for the targets.",
										Type:        "string",
									},
									"keySecret": apiextensionsv1.JSONSchemaProps{
										Description: "Secret containing the client key file for the targets.",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"key": apiextensionsv1.JSONSchemaProps{
												Description: "The key of the secret to select from.  Must be a valid secret key.",
												Type:        "string",
											},
											"name": apiextensionsv1.JSONSchemaProps{
												Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
												Type:        "string",
											},
											"optional": apiextensionsv1.JSONSchemaProps{
												Description: "Specify whether the Secret or its key must be defined",
												Type:        "boolean",
											},
										},
										Required: []string{"key"},
										Type:     "object",
										XMapType: P("atomic"),
									},
									"serverName": apiextensionsv1.JSONSchemaProps{
										Description: "Used to verify the hostname for the targets.",
										Type:        "string",
									},
								},
								Type: "object",
							},
							"vmProberSpec": apiextensionsv1.JSONSchemaProps{
								Description: "Specification for the prober to use for probing targets. The prober.URL parameter is required. Targets cannot be probed if left empty.",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"path": apiextensionsv1.JSONSchemaProps{
										Description: "Path to collect metrics from. Defaults to `/probe`.",
										Type:        "string",
									},
									"scheme": apiextensionsv1.JSONSchemaProps{
										Description: "HTTP scheme to use for scraping. Defaults to `http`.",
										Type:        "string",
									},
									"url": apiextensionsv1.JSONSchemaProps{
										Description: "Mandatory URL of the prober.",
										Type:        "string",
									},
								},
								Required: []string{"url"},
								Type:     "object",
							},
							"vm_scrape_params": apiextensionsv1.JSONSchemaProps{
								Description: "VMScrapeParams defines VictoriaMetrics specific scrape parametrs",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"disable_compression": apiextensionsv1.JSONSchemaProps{Type: "boolean"},
									"disable_keep_alive":  apiextensionsv1.JSONSchemaProps{Type: "boolean"},
									"headers": apiextensionsv1.JSONSchemaProps{
										Description: "Headers allows sending custom headers to scrape targets must be in of semicolon separated header with it's value eg: headerName: headerValue vmagent supports since 1.79.0 version",
										Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
										Type:        "array",
									},
									"metric_relabel_debug": apiextensionsv1.JSONSchemaProps{Type: "boolean"},
									"no_stale_markers":     apiextensionsv1.JSONSchemaProps{Type: "boolean"},
									"proxy_client_config": apiextensionsv1.JSONSchemaProps{
										Description: "ProxyClientConfig configures proxy auth settings for scraping See feature description https://docs.victoriametrics.com/vmagent.html#scraping-targets-via-a-proxy",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"basic_auth": apiextensionsv1.JSONSchemaProps{
												Description: "BasicAuth allow an endpoint to authenticate over basic authentication",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"password": apiextensionsv1.JSONSchemaProps{
														Description: "The secret in the service scrape namespace that contains the password for authentication. It must be at them same namespace as CRD",
														Properties: map[string]apiextensionsv1.JSONSchemaProps{
															"key": apiextensionsv1.JSONSchemaProps{
																Description: "The key of the secret to select from.  Must be a valid secret key.",
																Type:        "string",
															},
															"name": apiextensionsv1.JSONSchemaProps{
																Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																Type:        "string",
															},
															"optional": apiextensionsv1.JSONSchemaProps{
																Description: "Specify whether the Secret or its key must be defined",
																Type:        "boolean",
															},
														},
														Required: []string{"key"},
														Type:     "object",
														XMapType: P("atomic"),
													},
													"password_file": apiextensionsv1.JSONSchemaProps{
														Description: "PasswordFile defines path to password file at disk",
														Type:        "string",
													},
													"username": apiextensionsv1.JSONSchemaProps{
														Description: "The secret in the service scrape namespace that contains the username for authentication. It must be at them same namespace as CRD",
														Properties: map[string]apiextensionsv1.JSONSchemaProps{
															"key": apiextensionsv1.JSONSchemaProps{
																Description: "The key of the secret to select from.  Must be a valid secret key.",
																Type:        "string",
															},
															"name": apiextensionsv1.JSONSchemaProps{
																Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																Type:        "string",
															},
															"optional": apiextensionsv1.JSONSchemaProps{
																Description: "Specify whether the Secret or its key must be defined",
																Type:        "boolean",
															},
														},
														Required: []string{"key"},
														Type:     "object",
														XMapType: P("atomic"),
													},
												},
												Type: "object",
											},
											"bearer_token": apiextensionsv1.JSONSchemaProps{
												Description: "SecretKeySelector selects a key of a Secret.",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"key": apiextensionsv1.JSONSchemaProps{
														Description: "The key of the secret to select from.  Must be a valid secret key.",
														Type:        "string",
													},
													"name": apiextensionsv1.JSONSchemaProps{
														Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
														Type:        "string",
													},
													"optional": apiextensionsv1.JSONSchemaProps{
														Description: "Specify whether the Secret or its key must be defined",
														Type:        "boolean",
													},
												},
												Required: []string{"key"},
												Type:     "object",
												XMapType: P("atomic"),
											},
											"bearer_token_file": apiextensionsv1.JSONSchemaProps{Type: "string"},
											"tls_config": apiextensionsv1.JSONSchemaProps{
												Description: "TLSConfig specifies TLSConfig configuration parameters.",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"ca": apiextensionsv1.JSONSchemaProps{
														Description: "Stuct containing the CA cert to use for the targets.",
														Properties: map[string]apiextensionsv1.JSONSchemaProps{
															"configMap": apiextensionsv1.JSONSchemaProps{
																Description: "ConfigMap containing data to use for the targets.",
																Properties: map[string]apiextensionsv1.JSONSchemaProps{
																	"key": apiextensionsv1.JSONSchemaProps{
																		Description: "The key to select.",
																		Type:        "string",
																	},
																	"name": apiextensionsv1.JSONSchemaProps{
																		Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																		Type:        "string",
																	},
																	"optional": apiextensionsv1.JSONSchemaProps{
																		Description: "Specify whether the ConfigMap or its key must be defined",
																		Type:        "boolean",
																	},
																},
																Required: []string{"key"},
																Type:     "object",
																XMapType: P("atomic"),
															},
															"secret": apiextensionsv1.JSONSchemaProps{
																Description: "Secret containing data to use for the targets.",
																Properties: map[string]apiextensionsv1.JSONSchemaProps{
																	"key": apiextensionsv1.JSONSchemaProps{
																		Description: "The key of the secret to select from.  Must be a valid secret key.",
																		Type:        "string",
																	},
																	"name": apiextensionsv1.JSONSchemaProps{
																		Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																		Type:        "string",
																	},
																	"optional": apiextensionsv1.JSONSchemaProps{
																		Description: "Specify whether the Secret or its key must be defined",
																		Type:        "boolean",
																	},
																},
																Required: []string{"key"},
																Type:     "object",
																XMapType: P("atomic"),
															},
														},
														Type: "object",
													},
													"caFile": apiextensionsv1.JSONSchemaProps{
														Description: "Path to the CA cert in the container to use for the targets.",
														Type:        "string",
													},
													"cert": apiextensionsv1.JSONSchemaProps{
														Description: "Struct containing the client cert file for the targets.",
														Properties: map[string]apiextensionsv1.JSONSchemaProps{
															"configMap": apiextensionsv1.JSONSchemaProps{
																Description: "ConfigMap containing data to use for the targets.",
																Properties: map[string]apiextensionsv1.JSONSchemaProps{
																	"key": apiextensionsv1.JSONSchemaProps{
																		Description: "The key to select.",
																		Type:        "string",
																	},
																	"name": apiextensionsv1.JSONSchemaProps{
																		Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																		Type:        "string",
																	},
																	"optional": apiextensionsv1.JSONSchemaProps{
																		Description: "Specify whether the ConfigMap or its key must be defined",
																		Type:        "boolean",
																	},
																},
																Required: []string{"key"},
																Type:     "object",
																XMapType: P("atomic"),
															},
															"secret": apiextensionsv1.JSONSchemaProps{
																Description: "Secret containing data to use for the targets.",
																Properties: map[string]apiextensionsv1.JSONSchemaProps{
																	"key": apiextensionsv1.JSONSchemaProps{
																		Description: "The key of the secret to select from.  Must be a valid secret key.",
																		Type:        "string",
																	},
																	"name": apiextensionsv1.JSONSchemaProps{
																		Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																		Type:        "string",
																	},
																	"optional": apiextensionsv1.JSONSchemaProps{
																		Description: "Specify whether the Secret or its key must be defined",
																		Type:        "boolean",
																	},
																},
																Required: []string{"key"},
																Type:     "object",
																XMapType: P("atomic"),
															},
														},
														Type: "object",
													},
													"certFile": apiextensionsv1.JSONSchemaProps{
														Description: "Path to the client cert file in the container for the targets.",
														Type:        "string",
													},
													"insecureSkipVerify": apiextensionsv1.JSONSchemaProps{
														Description: "Disable target certificate validation.",
														Type:        "boolean",
													},
													"keyFile": apiextensionsv1.JSONSchemaProps{
														Description: "Path to the client key file in the container for the targets.",
														Type:        "string",
													},
													"keySecret": apiextensionsv1.JSONSchemaProps{
														Description: "Secret containing the client key file for the targets.",
														Properties: map[string]apiextensionsv1.JSONSchemaProps{
															"key": apiextensionsv1.JSONSchemaProps{
																Description: "The key of the secret to select from.  Must be a valid secret key.",
																Type:        "string",
															},
															"name": apiextensionsv1.JSONSchemaProps{
																Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																Type:        "string",
															},
															"optional": apiextensionsv1.JSONSchemaProps{
																Description: "Specify whether the Secret or its key must be defined",
																Type:        "boolean",
															},
														},
														Required: []string{"key"},
														Type:     "object",
														XMapType: P("atomic"),
													},
													"serverName": apiextensionsv1.JSONSchemaProps{
														Description: "Used to verify the hostname for the targets.",
														Type:        "string",
													},
												},
												Type: "object",
											},
										},
										Type: "object",
									},
									"relabel_debug":         apiextensionsv1.JSONSchemaProps{Type: "boolean"},
									"scrape_align_interval": apiextensionsv1.JSONSchemaProps{Type: "string"},
									"scrape_offset":         apiextensionsv1.JSONSchemaProps{Type: "string"},
									"stream_parse":          apiextensionsv1.JSONSchemaProps{Type: "boolean"},
								},
								Type: "object",
							},
						},
						Required: []string{"vmProberSpec"},
						Type:     "object",
					},
					"status": apiextensionsv1.JSONSchemaProps{
						Description: "VMProbeStatus defines the observed state of VMProbe",
						Type:        "object",
					},
				},
				Required: []string{"spec"},
				Type:     "object",
			}},
			Served:       true,
			Storage:      true,
			Subresources: &apiextensionsv1.CustomResourceSubresources{},
		}},
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "apiextensions.k8s.io/v1",
		Kind:       "CustomResourceDefinition",
	},
}
