// Copyright (c) 2023 Volvo Car Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package vmcrd

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var VmsinglesOperatorVictoriametricsComCRD = &apiextensionsv1.CustomResourceDefinition{
	ObjectMeta: metav1.ObjectMeta{
		Annotations: map[string]string{"controller-gen.kubebuilder.io/version": "v0.10.0"},
		Name:        "vmsingles.operator.victoriametrics.com",
	},
	Spec: apiextensionsv1.CustomResourceDefinitionSpec{
		Group: "operator.victoriametrics.com",
		Names: apiextensionsv1.CustomResourceDefinitionNames{
			Kind:     "VMSingle",
			ListKind: "VMSingleList",
			Plural:   "vmsingles",
			Singular: "vmsingle",
		},
		Scope: apiextensionsv1.ResourceScope("Namespaced"),
		Versions: []apiextensionsv1.CustomResourceDefinitionVersion{{
			Name: "v1beta1",
			Schema: &apiextensionsv1.CustomResourceValidation{OpenAPIV3Schema: &apiextensionsv1.JSONSchemaProps{
				Description: "VMSingle  is fast, cost-effective and scalable time-series database.",
				Properties: map[string]apiextensionsv1.JSONSchemaProps{
					"apiVersion": {
						Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
						Type:        "string",
					},
					"kind": {
						Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
						Type:        "string",
					},
					"metadata": {Type: "object"},
					"spec": {
						Description: "VMSingleSpec defines the desired state of VMSingle",
						Properties: map[string]apiextensionsv1.JSONSchemaProps{
							"affinity": {
								Description:            "Affinity If specified, the pod's scheduling constraints.",
								Type:                   "object",
								XPreserveUnknownFields: P(true),
							},
							"configMaps": {
								Description: "ConfigMaps is a list of ConfigMaps in the same namespace as the VMSingle object, which shall be mounted into the VMSingle Pods.",
								Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
								Type:        "array",
							},
							"containers": {
								Description: "Containers property allows to inject additions sidecars or to patch existing containers. It can be useful for proxies, backup, etc.",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description:            "A single application container that you want to run within a pod.",
									Required:               []string{"name"},
									Type:                   "object",
									XPreserveUnknownFields: P(true),
								}},
								Type: "array",
							},
							"dnsConfig": {
								Description: "Specifies the DNS parameters of a pod. Parameters specified here will be merged to the generated DNS configuration based on DNSPolicy.",
								Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{XPreserveUnknownFields: P(true)}},
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"nameservers": {
										Description: "A list of DNS name server IP addresses. This will be appended to the base nameservers generated from DNSPolicy. Duplicated nameservers will be removed.",
										Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
										Type:        "array",
									},
									"options": {
										Description: "A list of DNS resolver options. This will be merged with the base options generated from DNSPolicy. Duplicated entries will be removed. Resolution options given in Options will override those that appear in the base DNSPolicy.",
										Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
											Description: "PodDNSConfigOption defines DNS resolver options of a pod.",
											Properties: map[string]apiextensionsv1.JSONSchemaProps{
												"name": {
													Description: "Required.",
													Type:        "string",
												},
												"value": {Type: "string"},
											},
											Type: "object",
										}},
										Type: "array",
									},
									"searches": {
										Description: "A list of DNS search domains for host-name lookup. This will be appended to the base search paths generated from DNSPolicy. Duplicated search paths will be removed.",
										Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
										Type:        "array",
									},
								},
								Type: "object",
							},
							"dnsPolicy": {
								Description: "DNSPolicy sets DNS policy for the pod",
								Type:        "string",
							},
							"extraArgs": {
								AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
									Allows: true,
									Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
								},
								Description: "ExtraArgs that will be passed to  VMSingle pod for example remoteWrite.tmpDataPath: /tmp",
								Type:        "object",
							},
							"extraEnvs": {
								Description: "ExtraEnvs that will be added to VMSingle pod",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description: "EnvVar represents an environment variable present in a Container.",
									Properties: map[string]apiextensionsv1.JSONSchemaProps{
										"name": {
											Description: "Name of the environment variable. Must be a C_IDENTIFIER.",
											Type:        "string",
										},
										"value": {
											Description: "Variable references $(VAR_NAME) are expanded using the previously defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to \"\".",
											Type:        "string",
										},
									},
									Required:               []string{"name"},
									Type:                   "object",
									XPreserveUnknownFields: P(true),
								}},
								Type: "array",
							},
							"hostAliases": {
								Description: "HostAliases provides mapping for ip and hostname, that would be propagated to pod, cannot be used with HostNetwork.",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description: "HostAlias holds the mapping between IP and hostnames that will be injected as an entry in the pod's hosts file.",
									Properties: map[string]apiextensionsv1.JSONSchemaProps{
										"hostnames": {
											Description: "Hostnames for the above IP address.",
											Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
											Type:        "array",
										},
										"ip": {
											Description: "IP address of the host file entry.",
											Type:        "string",
										},
									},
									Type: "object",
								}},
								Type: "array",
							},
							"hostNetwork": {
								Description: "HostNetwork controls whether the pod may use the node network namespace",
								Type:        "boolean",
							},
							"image": {
								Description: "Image - docker image settings for VMSingle if no specified operator uses default config version",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"pullPolicy": {
										Description: "PullPolicy describes how to pull docker image",
										Type:        "string",
									},
									"repository": {
										Description: "Repository contains name of docker image + it's repository if needed",
										Type:        "string",
									},
									"tag": {
										Description: "Tag contains desired docker image version",
										Type:        "string",
									},
								},
								Type: "object",
							},
							"imagePullSecrets": {
								Description: "ImagePullSecrets An optional list of references to secrets in the same namespace to use for pulling images from registries see http://kubernetes.io/docs/user-guide/images#specifying-imagepullsecrets-on-a-pod",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description: "LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.",
									Properties: map[string]apiextensionsv1.JSONSchemaProps{"name": {
										Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
										Type:        "string",
									}},
									Type:     "object",
									XMapType: P("atomic"),
								}},
								Type: "array",
							},
							"initContainers": {
								Description: "InitContainers allows adding initContainers to the pod definition. Those can be used to e.g. fetch secrets for injection into the vmSingle configuration from external sources. Any errors during the execution of an initContainer will lead to a restart of the Pod. More info: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/ Using initContainers for any use case other then secret fetching is entirely outside the scope of what the maintainers will support and by doing so, you accept that this behaviour may break at any time without notice.",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description:            "A single application container that you want to run within a pod.",
									Required:               []string{"name"},
									Type:                   "object",
									XPreserveUnknownFields: P(true),
								}},
								Type: "array",
							},
							"insertPorts": {
								Description: "InsertPorts - additional listen ports for data ingestion.",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"graphitePort": {
										Description: "GraphitePort listen port",
										Type:        "string",
									},
									"influxPort": {
										Description: "InfluxPort listen port",
										Type:        "string",
									},
									"openTSDBHTTPPort": {
										Description: "OpenTSDBHTTPPort for http connections.",
										Type:        "string",
									},
									"openTSDBPort": {
										Description: "OpenTSDBPort for tcp and udp listen",
										Type:        "string",
									},
								},
								Type: "object",
							},
							"livenessProbe": {
								Description:            "LivenessProbe that will be added CRD pod",
								Type:                   "object",
								XPreserveUnknownFields: P(true),
							},
							"logFormat": {
								Description: "LogFormat for VMSingle to be configured with.",
								Enum:        []apiextensionsv1.JSON{{Raw: []byte("\"default\"")}, {Raw: []byte("\"json\"")}},
								Type:        "string",
							},
							"logLevel": {
								Description: "LogLevel for victoria metrics single to be configured with.",
								Enum:        []apiextensionsv1.JSON{{Raw: []byte("\"INFO\"")}, {Raw: []byte("\"WARN\"")}, {Raw: []byte("\"ERROR\"")}, {Raw: []byte("\"FATAL\"")}, {Raw: []byte("\"PANIC\"")}},
								Type:        "string",
							},
							"nodeSelector": {
								AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
									Allows: true,
									Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
								},
								Description: "NodeSelector Define which Nodes the Pods are scheduled on.",
								Type:        "object",
							},
							"podMetadata": {
								Description: "PodMetadata configures Labels and Annotations which are propagated to the VMSingle pods.",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"annotations": {
										AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
											Allows: true,
											Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
										},
										Description: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations",
										Type:        "object",
									},
									"labels": {
										AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
											Allows: true,
											Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
										},
										Description: "Labels Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels",
										Type:        "object",
									},
									"name": {
										Description: "Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names",
										Type:        "string",
									},
								},
								Type: "object",
							},
							"podSecurityPolicyName": {
								Description: "PodSecurityPolicyName - defines name for podSecurityPolicy in case of empty value, prefixedName will be used.",
								Type:        "string",
							},
							"port": {
								Description: "Port listen port",
								Type:        "string",
							},
							"priorityClassName": {
								Description: "PriorityClassName assigned to the Pods",
								Type:        "string",
							},
							"readinessGates": {
								Description: "ReadinessGates defines pod readiness gates",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description: "PodReadinessGate contains the reference to a pod condition",
									Properties: map[string]apiextensionsv1.JSONSchemaProps{"conditionType": {
										Description: "ConditionType refers to a condition in the pod's condition list with matching type.",
										Type:        "string",
									}},
									Required: []string{"conditionType"},
									Type:     "object",
								}},
								Type: "array",
							},
							"readinessProbe": {
								Description:            "ReadinessProbe that will be added CRD pod",
								Type:                   "object",
								XPreserveUnknownFields: P(true),
							},
							"removePvcAfterDelete": {
								Description: "RemovePvcAfterDelete - if true, controller adds ownership to pvc and after VMSingle objest deletion - pvc will be garbage collected by controller manager",
								Type:        "boolean",
							},
							"replicaCount": {
								Description: "ReplicaCount is the expected size of the VMSingle it can be 0 or 1 if you need more - use vm cluster",
								Format:      "int32",
								Type:        "integer",
							},
							"resources": {
								Description: "Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ if not defined default resources from operator config will be used",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"limits": {
										AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
											Allows: true,
											Schema: &apiextensionsv1.JSONSchemaProps{
												AnyOf:        []apiextensionsv1.JSONSchemaProps{{Type: "integer"}, {Type: "string"}},
												Pattern:      "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
												XIntOrString: true,
											},
										},
										Description: "Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/",
										Type:        "object",
									},
									"requests": {
										AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
											Allows: true,
											Schema: &apiextensionsv1.JSONSchemaProps{
												AnyOf:        []apiextensionsv1.JSONSchemaProps{{Type: "integer"}, {Type: "string"}},
												Pattern:      "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
												XIntOrString: true,
											},
										},
										Description: "Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/",
										Type:        "object",
									},
								},
								Type: "object",
							},
							"retentionPeriod": {
								Description: "RetentionPeriod for the stored metrics Note VictoriaMetrics has data/ and indexdb/ folders metrics from data/ removed eventually as soon as partition leaves retention period reverse index data at indexdb rotates once at the half of configured retention period https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#retention",
								Type:        "string",
							},
							"runtimeClassName": {
								Description: "RuntimeClassName - defines runtime class for kubernetes pod. https://kubernetes.io/docs/concepts/containers/runtime-class/",
								Type:        "string",
							},
							"schedulerName": {
								Description: "SchedulerName - defines kubernetes scheduler name",
								Type:        "string",
							},
							"secrets": {
								Description: "Secrets is a list of Secrets in the same namespace as the VMSingle object, which shall be mounted into the VMSingle Pods.",
								Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
								Type:        "array",
							},
							"securityContext": {
								Description:            "SecurityContext holds pod-level security attributes and common container settings. This defaults to the default PodSecurityContext.",
								Type:                   "object",
								XPreserveUnknownFields: P(true),
							},
							"serviceAccountName": {
								Description: "ServiceAccountName is the name of the ServiceAccount to use to run the VMSingle Pods.",
								Type:        "string",
							},
							"serviceScrapeSpec": {
								Description:            "ServiceScrapeSpec that will be added to vmselect VMServiceScrape spec",
								Required:               []string{"endpoints"},
								Type:                   "object",
								XPreserveUnknownFields: P(true),
							},
							"serviceSpec": {
								Description: "ServiceSpec that will be added to vmsingle service spec",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"metadata": {
										Description: "EmbeddedObjectMetadata defines objectMeta for additional service.",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"annotations": {
												AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
													Allows: true,
													Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
												},
												Description: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations",
												Type:        "object",
											},
											"labels": {
												AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
													Allows: true,
													Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
												},
												Description: "Labels Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels",
												Type:        "object",
											},
											"name": {
												Description: "Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names",
												Type:        "string",
											},
										},
										Type: "object",
									},
									"spec": {
										Description:            "ServiceSpec describes the attributes that a user creates on a service. More info: https://kubernetes.io/docs/concepts/services-networking/service/",
										Type:                   "object",
										XPreserveUnknownFields: P(true),
									},
								},
								Required: []string{"spec"},
								Type:     "object",
							},
							"startupProbe": {
								Description:            "StartupProbe that will be added to CRD pod",
								Type:                   "object",
								XPreserveUnknownFields: P(true),
							},
							"storage": {
								Description: "Storage is the definition of how storage will be used by the VMSingle by default it`s empty dir",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"accessModes": {
										Description: "accessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1",
										Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
										Type:        "array",
									},
									"dataSource": {
										Description: "dataSource field can be used to specify either: * An existing VolumeSnapshot object (snapshot.storage.k8s.io/VolumeSnapshot) * An existing PVC (PersistentVolumeClaim) If the provisioner or an external controller can support the specified data source, it will create a new volume based on the contents of the specified data source. If the AnyVolumeDataSource feature gate is enabled, this field will always have the same contents as the DataSourceRef field.",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"apiGroup": {
												Description: "APIGroup is the group for the resource being referenced. If APIGroup is not specified, the specified Kind must be in the core API group. For any other third-party types, APIGroup is required.",
												Type:        "string",
											},
											"kind": {
												Description: "Kind is the type of resource being referenced",
												Type:        "string",
											},
											"name": {
												Description: "Name is the name of resource being referenced",
												Type:        "string",
											},
										},
										Required: []string{"kind", "name"},
										Type:     "object",
										XMapType: P("atomic"),
									},
									"dataSourceRef": {
										Description: "dataSourceRef specifies the object from which to populate the volume with data, if a non-empty volume is desired. This may be any local object from a non-empty API group (non core object) or a PersistentVolumeClaim object. When this field is specified, volume binding will only succeed if the type of the specified object matches some installed volume populator or dynamic provisioner. This field will replace the functionality of the DataSource field and as such if both fields are non-empty, they must have the same value. For backwards compatibility, both fields (DataSource and DataSourceRef) will be set to the same value automatically if one of them is empty and the other is non-empty. There are two important differences between DataSource and DataSourceRef: * While DataSource only allows two specific types of objects, DataSourceRef allows any non-core object, as well as PersistentVolumeClaim objects. * While DataSource ignores disallowed values (dropping them), DataSourceRef preserves all values, and generates an error if a disallowed value is specified. (Beta) Using this field requires the AnyVolumeDataSource feature gate to be enabled.",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"apiGroup": {
												Description: "APIGroup is the group for the resource being referenced. If APIGroup is not specified, the specified Kind must be in the core API group. For any other third-party types, APIGroup is required.",
												Type:        "string",
											},
											"kind": {
												Description: "Kind is the type of resource being referenced",
												Type:        "string",
											},
											"name": {
												Description: "Name is the name of resource being referenced",
												Type:        "string",
											},
										},
										Required: []string{"kind", "name"},
										Type:     "object",
										XMapType: P("atomic"),
									},
									"resources": {
										Description: "resources represents the minimum resources the volume should have. If RecoverVolumeExpansionFailure feature is enabled users are allowed to specify resource requirements that are lower than previous value but must still be higher than capacity recorded in the status field of the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#resources",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"limits": {
												AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
													Allows: true,
													Schema: &apiextensionsv1.JSONSchemaProps{
														AnyOf:        []apiextensionsv1.JSONSchemaProps{{Type: "integer"}, {Type: "string"}},
														Pattern:      "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
														XIntOrString: true,
													},
												},
												Description: "Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/",
												Type:        "object",
											},
											"requests": {
												AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
													Allows: true,
													Schema: &apiextensionsv1.JSONSchemaProps{
														AnyOf:        []apiextensionsv1.JSONSchemaProps{{Type: "integer"}, {Type: "string"}},
														Pattern:      "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
														XIntOrString: true,
													},
												},
												Description: "Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/",
												Type:        "object",
											},
										},
										Type: "object",
									},
									"selector": {
										Description: "selector is a label query over volumes to consider for binding.",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"matchExpressions": {
												Description: "matchExpressions is a list of label selector requirements. The requirements are ANDed.",
												Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
													Description: "A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"key": {
															Description: "key is the label key that the selector applies to.",
															Type:        "string",
														},
														"operator": {
															Description: "operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.",
															Type:        "string",
														},
														"values": {
															Description: "values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.",
															Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
															Type:        "array",
														},
													},
													Required: []string{"key", "operator"},
													Type:     "object",
												}},
												Type: "array",
											},
											"matchLabels": {
												AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
													Allows: true,
													Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
												},
												Description: "matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed.",
												Type:        "object",
											},
										},
										Type:     "object",
										XMapType: P("atomic"),
									},
									"storageClassName": {
										Description: "storageClassName is the name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1",
										Type:        "string",
									},
									"volumeMode": {
										Description: "volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included in claim spec.",
										Type:        "string",
									},
									"volumeName": {
										Description: "volumeName is the binding reference to the PersistentVolume backing this claim.",
										Type:        "string",
									},
								},
								Type: "object",
							},
							"storageDataPath": {
								Description: "StorageDataPath disables spec.storage option and overrides arg for victoria-metrics binary --storageDataPath, its users responsibility to mount proper device into given path.",
								Type:        "string",
							},
							"storageMetadata": {
								Description: "StorageMeta defines annotations and labels attached to PVC for given vmsingle CR",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"annotations": {
										AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
											Allows: true,
											Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
										},
										Description: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations",
										Type:        "object",
									},
									"labels": {
										AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
											Allows: true,
											Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
										},
										Description: "Labels Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels",
										Type:        "object",
									},
									"name": {
										Description: "Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names",
										Type:        "string",
									},
								},
								Type: "object",
							},
							"streamAggrConfig": {
								Description: "StreamAggrConfig defines stream aggregation configuration for VMSingle",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"dedupInterval": {
										Description: "Allows setting different de-duplication intervals per each configured remote storage",
										Type:        "string",
									},
									"keepInput": {
										Description: "Allows writing both raw and aggregate data",
										Type:        "boolean",
									},
									"rules": {
										Description: "Stream aggregation rules",
										Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
											Description: "StreamAggrRule defines the rule in stream aggregation config",
											Properties: map[string]apiextensionsv1.JSONSchemaProps{
												"by": {
													Description: `
By is an optional list of labels for grouping input series. 
 See also Without. 
 If neither By nor Without are set, then the Outputs are calculated individually per each input time series.
`,
													Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
													Type:  "array",
												},
												"input_relabel_configs": {
													Description: "InputRelabelConfigs is an optional relabeling rules, which are applied on the input before aggregation.",
													Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
														Description: "RelabelConfig allows dynamic rewriting of the label set, being applied to samples before ingestion. It defines `<metric_relabel_configs>`-section of configuration. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs",
														Properties: map[string]apiextensionsv1.JSONSchemaProps{
															"action": {
																Description: "Action to perform based on regex matching. Default is 'replace'",
																Type:        "string",
															},
															"if": {
																Description: "If represents metricsQL match expression: '{__name__=~\"foo_.*\"}'",
																Type:        "string",
															},
															"labels": {
																AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
																	Allows: true,
																	Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
																},
																Description: "Labels is used together with Match for `action: graphite`",
																Type:        "object",
															},
															"match": {
																Description: "Match is used together with Labels for `action: graphite`",
																Type:        "string",
															},
															"modulus": {
																Description: "Modulus to take of the hash of the source label values.",
																Format:      "int64",
																Type:        "integer",
															},
															"regex": {
																Description: "Regular expression against which the extracted value is matched. Default is '(.*)'",
																Type:        "string",
															},
															"replacement": {
																Description: "Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available. Default is '$1'",
																Type:        "string",
															},
															"separator": {
																Description: "Separator placed between concatenated source label values. default is ';'.",
																Type:        "string",
															},
															"sourceLabels": {
																Description: "The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions.",
																Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
																Type:        "array",
															},
															"source_labels": {
																Description: "UnderScoreSourceLabels - additional form of source labels source_labels for compatibility with original relabel config. if set  both sourceLabels and source_labels, sourceLabels has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
																Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
																Type:        "array",
															},
															"targetLabel": {
																Description: "Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available.",
																Type:        "string",
															},
															"target_label": {
																Description: "UnderScoreTargetLabel - additional form of target label - target_label for compatibility with original relabel config. if set  both targetLabel and target_label, targetLabel has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
																Type:        "string",
															},
														},
														Type: "object",
													}},
													Type: "array",
												},
												"interval": {
													Description: "Interval is the interval between aggregations.",
													Type:        "string",
												},
												"match": {
													Description: `
Match is a label selector for filtering time series for the given selector. 
 If the match isn't set, then all the input time series are processed.
`,
													Type: "string",
												},
												"output_relabel_configs": {
													Description: "OutputRelabelConfigs is an optional relabeling rules, which are applied on the aggregated output before being sent to remote storage.",
													Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
														Description: "RelabelConfig allows dynamic rewriting of the label set, being applied to samples before ingestion. It defines `<metric_relabel_configs>`-section of configuration. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs",
														Properties: map[string]apiextensionsv1.JSONSchemaProps{
															"action": {
																Description: "Action to perform based on regex matching. Default is 'replace'",
																Type:        "string",
															},
															"if": {
																Description: "If represents metricsQL match expression: '{__name__=~\"foo_.*\"}'",
																Type:        "string",
															},
															"labels": {
																AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
																	Allows: true,
																	Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
																},
																Description: "Labels is used together with Match for `action: graphite`",
																Type:        "object",
															},
															"match": {
																Description: "Match is used together with Labels for `action: graphite`",
																Type:        "string",
															},
															"modulus": {
																Description: "Modulus to take of the hash of the source label values.",
																Format:      "int64",
																Type:        "integer",
															},
															"regex": {
																Description: "Regular expression against which the extracted value is matched. Default is '(.*)'",
																Type:        "string",
															},
															"replacement": {
																Description: "Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available. Default is '$1'",
																Type:        "string",
															},
															"separator": {
																Description: "Separator placed between concatenated source label values. default is ';'.",
																Type:        "string",
															},
															"sourceLabels": {
																Description: "The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions.",
																Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
																Type:        "array",
															},
															"source_labels": {
																Description: "UnderScoreSourceLabels - additional form of source labels source_labels for compatibility with original relabel config. if set  both sourceLabels and source_labels, sourceLabels has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
																Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
																Type:        "array",
															},
															"targetLabel": {
																Description: "Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available.",
																Type:        "string",
															},
															"target_label": {
																Description: "UnderScoreTargetLabel - additional form of target label - target_label for compatibility with original relabel config. if set  both targetLabel and target_label, targetLabel has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
																Type:        "string",
															},
														},
														Type: "object",
													}},
													Type: "array",
												},
												"outputs": {
													Description: `
Outputs is a list of output aggregate functions to produce. 
 The following names are allowed: 
 - total - aggregates input counters - increase - counts the increase over input counters - count_series - counts the input series - count_samples - counts the input samples - sum_samples - sums the input samples - last - the last biggest sample value - min - the minimum sample value - max - the maximum sample value - avg - the average value across all the samples - stddev - standard deviation across all the samples - stdvar - standard variance across all the samples - histogram_bucket - creates VictoriaMetrics histogram for input samples - quantiles(phi1, ..., phiN) - quantiles' estimation for phi in the range [0..1] 
 The output time series will have the following names: 
 input_name:aggr_<interval>_<output>
`,
													Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
													Type:  "array",
												},
												"without": {
													Description: `
Without is an optional list of labels, which must be excluded when grouping input series. 
 See also By. 
 If neither By nor Without are set, then the Outputs are calculated individually per each input time series.
`,
													Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
													Type:  "array",
												},
											},
											Required: []string{"interval", "outputs"},
											Type:     "object",
										}},
										Type: "array",
									},
								},
								Required: []string{"rules"},
								Type:     "object",
							},
							"terminationGracePeriodSeconds": {
								Description: "TerminationGracePeriodSeconds period for container graceful termination",
								Format:      "int64",
								Type:        "integer",
							},
							"tolerations": {
								Description: "Tolerations If specified, the pod's tolerations.",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description: "The pod this Toleration is attached to tolerates any taint that matches the triple <key,value,effect> using the matching operator <operator>.",
									Properties: map[string]apiextensionsv1.JSONSchemaProps{
										"effect": {
											Description: "Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.",
											Type:        "string",
										},
										"key": {
											Description: "Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys.",
											Type:        "string",
										},
										"operator": {
											Description: "Operator represents a key's relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category.",
											Type:        "string",
										},
										"tolerationSeconds": {
											Description: "TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system.",
											Format:      "int64",
											Type:        "integer",
										},
										"value": {
											Description: "Value is the taint value the toleration matches to. If the operator is Exists, the value should be empty, otherwise just a regular string.",
											Type:        "string",
										},
									},
									Type: "object",
								}},
								Type: "array",
							},
							"topologySpreadConstraints": {
								Description: "TopologySpreadConstraints embedded kubernetes pod configuration option, controls how pods are spread across your cluster among failure-domains such as regions, zones, nodes, and other user-defined topology domains https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description:            "TopologySpreadConstraint specifies how to spread matching pods among the given topology.",
									Required:               []string{"maxSkew", "topologyKey", "whenUnsatisfiable"},
									Type:                   "object",
									XPreserveUnknownFields: P(true),
								}},
								Type: "array",
							},
							"vmBackup": {
								Description: "VMBackup configuration for backup",
								Properties: map[string]apiextensionsv1.JSONSchemaProps{
									"acceptEULA": {
										Description: "AcceptEULA accepts enterprise feature usage, must be set to true. otherwise backupmanager cannot be added to single/cluster version. https://victoriametrics.com/legal/eula/",
										Type:        "boolean",
									},
									"concurrency": {
										Description: "Defines number of concurrent workers. Higher concurrency may reduce backup duration (default 10)",
										Format:      "int32",
										Type:        "integer",
									},
									"credentialsSecret": {
										Description: "CredentialsSecret is secret in the same namespace for access to remote storage The secret is mounted into /etc/vm/creds.",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"key": {
												Description: "The key of the secret to select from.  Must be a valid secret key.",
												Type:        "string",
											},
											"name": {
												Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
												Type:        "string",
											},
											"optional": {
												Description: "Specify whether the Secret or its key must be defined",
												Type:        "boolean",
											},
										},
										Required: []string{"key"},
										Type:     "object",
										XMapType: P("atomic"),
									},
									"customS3Endpoint": {
										Description: "Custom S3 endpoint for use with S3-compatible storages (e.g. MinIO). S3 is used if not set",
										Type:        "string",
									},
									"destination": {
										Description: "Defines destination for backup",
										Type:        "string",
									},
									"destinationDisableSuffixAdd": {
										Description: "DestinationDisableSuffixAdd - disables suffix adding for cluster version backups each vmstorage backup must have unique backup folder so operator adds POD_NAME as suffix for backup destination folder.",
										Type:        "boolean",
									},
									"disableDaily": {
										Description: "Defines if daily backups disabled (default false)",
										Type:        "boolean",
									},
									"disableHourly": {
										Description: "Defines if hourly backups disabled (default false)",
										Type:        "boolean",
									},
									"disableMonthly": {
										Description: "Defines if monthly backups disabled (default false)",
										Type:        "boolean",
									},
									"disableWeekly": {
										Description: "Defines if weekly backups disabled (default false)",
										Type:        "boolean",
									},
									"extraArgs": {
										AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
											Allows: true,
											Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
										},
										Description: "extra args like maxBytesPerSecond default 0",
										Type:        "object",
									},
									"extraEnvs": {
										Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
											Description: "EnvVar represents an environment variable present in a Container.",
											Properties: map[string]apiextensionsv1.JSONSchemaProps{
												"name": {
													Description: "Name of the environment variable. Must be a C_IDENTIFIER.",
													Type:        "string",
												},
												"value": {
													Description: "Variable references $(VAR_NAME) are expanded using the previously defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to \"\".",
													Type:        "string",
												},
												"valueFrom": {
													Description: "Source for the environment variable's value. Cannot be used if value is not empty.",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"configMapKeyRef": {
															Description: "Selects a key of a ConfigMap.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"key": {
																	Description: "The key to select.",
																	Type:        "string",
																},
																"name": {
																	Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																	Type:        "string",
																},
																"optional": {
																	Description: "Specify whether the ConfigMap or its key must be defined",
																	Type:        "boolean",
																},
															},
															Required: []string{"key"},
															Type:     "object",
															XMapType: P("atomic"),
														},
														"fieldRef": {
															Description: "Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"apiVersion": {
																	Description: "Version of the schema the FieldPath is written in terms of, defaults to \"v1\".",
																	Type:        "string",
																},
																"fieldPath": {
																	Description: "Path of the field to select in the specified API version.",
																	Type:        "string",
																},
															},
															Required: []string{"fieldPath"},
															Type:     "object",
															XMapType: P("atomic"),
														},
														"resourceFieldRef": {
															Description: "Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"containerName": {
																	Description: "Container name: required for volumes, optional for env vars",
																	Type:        "string",
																},
																"divisor": {
																	AnyOf:        []apiextensionsv1.JSONSchemaProps{{Type: "integer"}, {Type: "string"}},
																	Description:  "Specifies the output format of the exposed resources, defaults to \"1\"",
																	Pattern:      "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
																	XIntOrString: true,
																},
																"resource": {
																	Description: "Required: resource to select",
																	Type:        "string",
																},
															},
															Required: []string{"resource"},
															Type:     "object",
															XMapType: P("atomic"),
														},
														"secretKeyRef": {
															Description: "Selects a key of a secret in the pod's namespace",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"key": {
																	Description: "The key of the secret to select from.  Must be a valid secret key.",
																	Type:        "string",
																},
																"name": {
																	Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																	Type:        "string",
																},
																"optional": {
																	Description: "Specify whether the Secret or its key must be defined",
																	Type:        "boolean",
																},
															},
															Required: []string{"key"},
															Type:     "object",
															XMapType: P("atomic"),
														},
													},
													Type: "object",
												},
											},
											Required: []string{"name"},
											Type:     "object",
										}},
										Type: "array",
									},
									"image": {
										Description: "Image - docker image settings for VMBackuper",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"pullPolicy": {
												Description: "PullPolicy describes how to pull docker image",
												Type:        "string",
											},
											"repository": {
												Description: "Repository contains name of docker image + it's repository if needed",
												Type:        "string",
											},
											"tag": {
												Description: "Tag contains desired docker image version",
												Type:        "string",
											},
										},
										Type: "object",
									},
									"logFormat": {
										Description: "LogFormat for VMSelect to be configured with. default or json",
										Enum:        []apiextensionsv1.JSON{{Raw: []byte("\"default\"")}, {Raw: []byte("\"json\"")}},
										Type:        "string",
									},
									"logLevel": {
										Description: "LogLevel for VMSelect to be configured with.",
										Enum:        []apiextensionsv1.JSON{{Raw: []byte("\"INFO\"")}, {Raw: []byte("\"WARN\"")}, {Raw: []byte("\"ERROR\"")}, {Raw: []byte("\"FATAL\"")}, {Raw: []byte("\"PANIC\"")}},
										Type:        "string",
									},
									"port": {
										Description: "Port for health check connections",
										Type:        "string",
									},
									"resources": {
										Description: "Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ if not defined default resources from operator config will be used",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{
											"limits": {
												AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
													Allows: true,
													Schema: &apiextensionsv1.JSONSchemaProps{
														AnyOf:        []apiextensionsv1.JSONSchemaProps{{Type: "integer"}, {Type: "string"}},
														Pattern:      "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
														XIntOrString: true,
													},
												},
												Description: "Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/",
												Type:        "object",
											},
											"requests": {
												AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
													Allows: true,
													Schema: &apiextensionsv1.JSONSchemaProps{
														AnyOf:        []apiextensionsv1.JSONSchemaProps{{Type: "integer"}, {Type: "string"}},
														Pattern:      "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
														XIntOrString: true,
													},
												},
												Description: "Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/",
												Type:        "object",
											},
										},
										Type: "object",
									},
									"restore": {
										Description: "Restore Allows to enable restore options for pod Read more: https://docs.victoriametrics.com/vmbackupmanager.html#restore-commands",
										Properties: map[string]apiextensionsv1.JSONSchemaProps{"onStart": {
											Description: "OnStart defines configuration for restore on pod start",
											Properties: map[string]apiextensionsv1.JSONSchemaProps{"enabled": {
												Description: "Enabled defines if restore on start enabled",
												Type:        "boolean",
											}},
											Type: "object",
										}},
										Type: "object",
									},
									"snapshotCreateURL": {
										Description: "SnapshotCreateURL overwrites url for snapshot create",
										Type:        "string",
									},
									"snapshotDeleteURL": {
										Description: "SnapShotDeleteURL overwrites url for snapshot delete",
										Type:        "string",
									},
									"volumeMounts": {
										Description: "VolumeMounts allows configuration of additional VolumeMounts on the output Deployment definition. VolumeMounts specified will be appended to other VolumeMounts in the vmbackupmanager container, that are generated as a result of StorageSpec objects.",
										Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
											Description: "VolumeMount describes a mounting of a Volume within a container.",
											Properties: map[string]apiextensionsv1.JSONSchemaProps{
												"mountPath": {
													Description: "Path within the container at which the volume should be mounted.  Must not contain ':'.",
													Type:        "string",
												},
												"mountPropagation": {
													Description: "mountPropagation determines how mounts are propagated from the host to container and the other way around. When not set, MountPropagationNone is used. This field is beta in 1.10.",
													Type:        "string",
												},
												"name": {
													Description: "This must match the Name of a Volume.",
													Type:        "string",
												},
												"readOnly": {
													Description: "Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false.",
													Type:        "boolean",
												},
												"subPath": {
													Description: "Path within the volume from which the container's volume should be mounted. Defaults to \"\" (volume's root).",
													Type:        "string",
												},
												"subPathExpr": {
													Description: "Expanded path within the volume from which the container's volume should be mounted. Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container's environment. Defaults to \"\" (volume's root). SubPathExpr and SubPath are mutually exclusive.",
													Type:        "string",
												},
											},
											Required: []string{"mountPath", "name"},
											Type:     "object",
										}},
										Type: "array",
									},
								},
								Required: []string{"acceptEULA"},
								Type:     "object",
							},
							"volumeMounts": {
								Description: "VolumeMounts allows configuration of additional VolumeMounts on the output Deployment definition. VolumeMounts specified will be appended to other VolumeMounts in the VMSingle container, that are generated as a result of StorageSpec objects.",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description: "VolumeMount describes a mounting of a Volume within a container.",
									Properties: map[string]apiextensionsv1.JSONSchemaProps{
										"mountPath": {
											Description: "Path within the container at which the volume should be mounted.  Must not contain ':'.",
											Type:        "string",
										},
										"mountPropagation": {
											Description: "mountPropagation determines how mounts are propagated from the host to container and the other way around. When not set, MountPropagationNone is used. This field is beta in 1.10.",
											Type:        "string",
										},
										"name": {
											Description: "This must match the Name of a Volume.",
											Type:        "string",
										},
										"readOnly": {
											Description: "Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false.",
											Type:        "boolean",
										},
										"subPath": {
											Description: "Path within the volume from which the container's volume should be mounted. Defaults to \"\" (volume's root).",
											Type:        "string",
										},
										"subPathExpr": {
											Description: "Expanded path within the volume from which the container's volume should be mounted. Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container's environment. Defaults to \"\" (volume's root). SubPathExpr and SubPath are mutually exclusive.",
											Type:        "string",
										},
									},
									Required: []string{"mountPath", "name"},
									Type:     "object",
								}},
								Type: "array",
							},
							"volumes": {
								Description: "Volumes allows configuration of additional volumes on the output deploy definition. Volumes specified will be appended to other volumes that are generated as a result of StorageSpec objects.",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description:            "Volume represents a named volume in a pod that may be accessed by any container in the pod.",
									Required:               []string{"name"},
									Type:                   "object",
									XPreserveUnknownFields: P(true),
								}},
								Type: "array",
							},
						},
						Required: []string{"retentionPeriod"},
						Type:     "object",
					},
					"status": {
						Description: "VMSingleStatus defines the observed state of VMSingle",
						Properties: map[string]apiextensionsv1.JSONSchemaProps{
							"availableReplicas": {
								Description: "AvailableReplicas Total number of available pods (ready for at least minReadySeconds) targeted by this VMAlert cluster.",
								Format:      "int32",
								Type:        "integer",
							},
							"replicas": {
								Description: "ReplicaCount Total number of non-terminated pods targeted by this VMAlert cluster (their labels match the selector).",
								Format:      "int32",
								Type:        "integer",
							},
							"unavailableReplicas": {
								Description: "UnavailableReplicas Total number of unavailable pods targeted by this VMAlert cluster.",
								Format:      "int32",
								Type:        "integer",
							},
							"updatedReplicas": {
								Description: "UpdatedReplicas Total number of non-terminated pods targeted by this VMAlert cluster that have the desired version spec.",
								Format:      "int32",
								Type:        "integer",
							},
						},
						Required: []string{"availableReplicas", "replicas", "unavailableReplicas", "updatedReplicas"},
						Type:     "object",
					},
				},
				Type: "object",
			}},
			Served:       true,
			Storage:      true,
			Subresources: &apiextensionsv1.CustomResourceSubresources{},
		}},
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "apiextensions.k8s.io/v1",
		Kind:       "CustomResourceDefinition",
	},
}
