// Copyright (c) 2023 Volvo Car Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package vmcrd

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var VmstaticscrapesOperatorVictoriametricsComCRD = &apiextensionsv1.CustomResourceDefinition{
	ObjectMeta: metav1.ObjectMeta{
		Annotations: map[string]string{"controller-gen.kubebuilder.io/version": "v0.10.0"},
		Name:        "vmstaticscrapes.operator.victoriametrics.com",
	},
	Spec: apiextensionsv1.CustomResourceDefinitionSpec{
		Group: "operator.victoriametrics.com",
		Names: apiextensionsv1.CustomResourceDefinitionNames{
			Kind:     "VMStaticScrape",
			ListKind: "VMStaticScrapeList",
			Plural:   "vmstaticscrapes",
			Singular: "vmstaticscrape",
		},
		Scope: apiextensionsv1.ResourceScope("Namespaced"),
		Versions: []apiextensionsv1.CustomResourceDefinitionVersion{{
			Name: "v1beta1",
			Schema: &apiextensionsv1.CustomResourceValidation{OpenAPIV3Schema: &apiextensionsv1.JSONSchemaProps{
				Description: "VMStaticScrape  defines static targets configuration for scraping.",
				Properties: map[string]apiextensionsv1.JSONSchemaProps{
					"apiVersion": {
						Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
						Type:        "string",
					},
					"kind": {
						Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
						Type:        "string",
					},
					"metadata": {Type: "object"},
					"spec": {
						Description: "VMStaticScrapeSpec defines the desired state of VMStaticScrape.",
						Properties: map[string]apiextensionsv1.JSONSchemaProps{
							"jobName": {
								Description: "JobName name of job.",
								Type:        "string",
							},
							"sampleLimit": {
								Description: "SampleLimit defines per-scrape limit on number of scraped samples that will be accepted.",
								Format:      "int64",
								Type:        "integer",
							},
							"targetEndpoints": {
								Description: "A list of target endpoints to scrape metrics from.",
								Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
									Description: "TargetEndpoint defines single static target endpoint.",
									Properties: map[string]apiextensionsv1.JSONSchemaProps{
										"authorization": {
											Description: "Authorization with http header Authorization",
											Properties: map[string]apiextensionsv1.JSONSchemaProps{
												"credentials": {
													Description: "Reference to the secret with value for authorization",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"key": {
															Description: "The key of the secret to select from.  Must be a valid secret key.",
															Type:        "string",
														},
														"name": {
															Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
															Type:        "string",
														},
														"optional": {
															Description: "Specify whether the Secret or its key must be defined",
															Type:        "boolean",
														},
													},
													Required: []string{"key"},
													Type:     "object",
													XMapType: P("atomic"),
												},
												"credentialsFile": {
													Description: "File with value for authorization",
													Type:        "string",
												},
												"type": {
													Description: "Type of authorization, default to bearer",
													Type:        "string",
												},
											},
											Type: "object",
										},
										"basicAuth": {
											Description: "BasicAuth allow an endpoint to authenticate over basic authentication More info: https://prometheus.io/docs/operating/configuration/#endpoints",
											Properties: map[string]apiextensionsv1.JSONSchemaProps{
												"password": {
													Description: "The secret in the service scrape namespace that contains the password for authentication. It must be at them same namespace as CRD",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"key": {
															Description: "The key of the secret to select from.  Must be a valid secret key.",
															Type:        "string",
														},
														"name": {
															Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
															Type:        "string",
														},
														"optional": {
															Description: "Specify whether the Secret or its key must be defined",
															Type:        "boolean",
														},
													},
													Required: []string{"key"},
													Type:     "object",
													XMapType: P("atomic"),
												},
												"password_file": {
													Description: "PasswordFile defines path to password file at disk",
													Type:        "string",
												},
												"username": {
													Description: "The secret in the service scrape namespace that contains the username for authentication. It must be at them same namespace as CRD",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"key": {
															Description: "The key of the secret to select from.  Must be a valid secret key.",
															Type:        "string",
														},
														"name": {
															Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
															Type:        "string",
														},
														"optional": {
															Description: "Specify whether the Secret or its key must be defined",
															Type:        "boolean",
														},
													},
													Required: []string{"key"},
													Type:     "object",
													XMapType: P("atomic"),
												},
											},
											Type: "object",
										},
										"bearerTokenFile": {
											Description: "File to read bearer token for scraping targets.",
											Type:        "string",
										},
										"bearerTokenSecret": {
											Description: "Secret to mount to read bearer token for scraping targets. The secret needs to be in the same namespace as the service scrape and accessible by the victoria-metrics operator.",
											Nullable:    true,
											Properties: map[string]apiextensionsv1.JSONSchemaProps{
												"key": {
													Description: "The key of the secret to select from.  Must be a valid secret key.",
													Type:        "string",
												},
												"name": {
													Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
													Type:        "string",
												},
												"optional": {
													Description: "Specify whether the Secret or its key must be defined",
													Type:        "boolean",
												},
											},
											Required: []string{"key"},
											Type:     "object",
											XMapType: P("atomic"),
										},
										"follow_redirects": {
											Description: "FollowRedirects controls redirects for scraping.",
											Type:        "boolean",
										},
										"honorLabels": {
											Description: "HonorLabels chooses the metric's labels on collisions with target labels.",
											Type:        "boolean",
										},
										"honorTimestamps": {
											Description: "HonorTimestamps controls whether vmagent respects the timestamps present in scraped data.",
											Type:        "boolean",
										},
										"interval": {
											Description: "Interval at which metrics should be scraped",
											Type:        "string",
										},
										"labels": {
											AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
												Allows: true,
												Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
											},
											Description: "Labels static labels for targets.",
											Type:        "object",
										},
										"metricRelabelConfigs": {
											Description: "MetricRelabelConfigs to apply to samples before ingestion.",
											Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
												Description: "RelabelConfig allows dynamic rewriting of the label set, being applied to samples before ingestion. It defines `<metric_relabel_configs>`-section of configuration. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"action": {
														Description: "Action to perform based on regex matching. Default is 'replace'",
														Type:        "string",
													},
													"if": {
														Description: "If represents metricsQL match expression: '{__name__=~\"foo_.*\"}'",
														Type:        "string",
													},
													"labels": {
														AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
															Allows: true,
															Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
														},
														Description: "Labels is used together with Match for `action: graphite`",
														Type:        "object",
													},
													"match": {
														Description: "Match is used together with Labels for `action: graphite`",
														Type:        "string",
													},
													"modulus": {
														Description: "Modulus to take of the hash of the source label values.",
														Format:      "int64",
														Type:        "integer",
													},
													"regex": {
														Description: "Regular expression against which the extracted value is matched. Default is '(.*)'",
														Type:        "string",
													},
													"replacement": {
														Description: "Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available. Default is '$1'",
														Type:        "string",
													},
													"separator": {
														Description: "Separator placed between concatenated source label values. default is ';'.",
														Type:        "string",
													},
													"sourceLabels": {
														Description: "The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions.",
														Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
														Type:        "array",
													},
													"source_labels": {
														Description: "UnderScoreSourceLabels - additional form of source labels source_labels for compatibility with original relabel config. if set  both sourceLabels and source_labels, sourceLabels has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
														Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
														Type:        "array",
													},
													"targetLabel": {
														Description: "Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available.",
														Type:        "string",
													},
													"target_label": {
														Description: "UnderScoreTargetLabel - additional form of target label - target_label for compatibility with original relabel config. if set  both targetLabel and target_label, targetLabel has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
														Type:        "string",
													},
												},
												Type: "object",
											}},
											Type: "array",
										},
										"oauth2": {
											Description: "OAuth2 defines auth configuration",
											Properties: map[string]apiextensionsv1.JSONSchemaProps{
												"client_id": {
													Description: "The secret or configmap containing the OAuth2 client id",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"configMap": {
															Description: "ConfigMap containing data to use for the targets.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"key": {
																	Description: "The key to select.",
																	Type:        "string",
																},
																"name": {
																	Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																	Type:        "string",
																},
																"optional": {
																	Description: "Specify whether the ConfigMap or its key must be defined",
																	Type:        "boolean",
																},
															},
															Required: []string{"key"},
															Type:     "object",
															XMapType: P("atomic"),
														},
														"secret": {
															Description: "Secret containing data to use for the targets.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"key": {
																	Description: "The key of the secret to select from.  Must be a valid secret key.",
																	Type:        "string",
																},
																"name": {
																	Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																	Type:        "string",
																},
																"optional": {
																	Description: "Specify whether the Secret or its key must be defined",
																	Type:        "boolean",
																},
															},
															Required: []string{"key"},
															Type:     "object",
															XMapType: P("atomic"),
														},
													},
													Type: "object",
												},
												"client_secret": {
													Description: "The secret containing the OAuth2 client secret",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"key": {
															Description: "The key of the secret to select from.  Must be a valid secret key.",
															Type:        "string",
														},
														"name": {
															Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
															Type:        "string",
														},
														"optional": {
															Description: "Specify whether the Secret or its key must be defined",
															Type:        "boolean",
														},
													},
													Required: []string{"key"},
													Type:     "object",
													XMapType: P("atomic"),
												},
												"client_secret_file": {
													Description: "ClientSecretFile defines path for client secret file.",
													Type:        "string",
												},
												"endpoint_params": {
													AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
														Allows: true,
														Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
													},
													Description: "Parameters to append to the token URL",
													Type:        "object",
												},
												"scopes": {
													Description: "OAuth2 scopes used for the token request",
													Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
													Type:        "array",
												},
												"token_url": {
													Description: "The URL to fetch the token from",
													MinLength:   P(int64(1)),
													Type:        "string",
												},
											},
											Required: []string{"client_id", "token_url"},
											Type:     "object",
										},
										"params": {
											AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
												Allows: true,
												Schema: &apiextensionsv1.JSONSchemaProps{
													Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
													Type:  "array",
												},
											},
											Description: "Optional HTTP URL parameters",
											Type:        "object",
										},
										"path": {
											Description: "HTTP path to scrape for metrics.",
											Type:        "string",
										},
										"port": {
											Description: "Default port for target.",
											Type:        "string",
										},
										"proxyURL": {
											Description: "ProxyURL eg http://proxyserver:2195 Directs scrapes to proxy through this endpoint.",
											Type:        "string",
										},
										"relabelConfigs": {
											Description: "RelabelConfigs to apply to samples before scraping. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config",
											Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{
												Description: "RelabelConfig allows dynamic rewriting of the label set, being applied to samples before ingestion. It defines `<metric_relabel_configs>`-section of configuration. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs",
												Properties: map[string]apiextensionsv1.JSONSchemaProps{
													"action": {
														Description: "Action to perform based on regex matching. Default is 'replace'",
														Type:        "string",
													},
													"if": {
														Description: "If represents metricsQL match expression: '{__name__=~\"foo_.*\"}'",
														Type:        "string",
													},
													"labels": {
														AdditionalProperties: &apiextensionsv1.JSONSchemaPropsOrBool{
															Allows: true,
															Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"},
														},
														Description: "Labels is used together with Match for `action: graphite`",
														Type:        "object",
													},
													"match": {
														Description: "Match is used together with Labels for `action: graphite`",
														Type:        "string",
													},
													"modulus": {
														Description: "Modulus to take of the hash of the source label values.",
														Format:      "int64",
														Type:        "integer",
													},
													"regex": {
														Description: "Regular expression against which the extracted value is matched. Default is '(.*)'",
														Type:        "string",
													},
													"replacement": {
														Description: "Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available. Default is '$1'",
														Type:        "string",
													},
													"separator": {
														Description: "Separator placed between concatenated source label values. default is ';'.",
														Type:        "string",
													},
													"sourceLabels": {
														Description: "The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions.",
														Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
														Type:        "array",
													},
													"source_labels": {
														Description: "UnderScoreSourceLabels - additional form of source labels source_labels for compatibility with original relabel config. if set  both sourceLabels and source_labels, sourceLabels has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
														Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
														Type:        "array",
													},
													"targetLabel": {
														Description: "Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available.",
														Type:        "string",
													},
													"target_label": {
														Description: "UnderScoreTargetLabel - additional form of target label - target_label for compatibility with original relabel config. if set  both targetLabel and target_label, targetLabel has priority. for details https://github.com/VictoriaMetrics/operator/issues/131",
														Type:        "string",
													},
												},
												Type: "object",
											}},
											Type: "array",
										},
										"sampleLimit": {
											Description: "SampleLimit defines per-scrape limit on number of scraped samples that will be accepted.",
											Format:      "int64",
											Type:        "integer",
										},
										"scheme": {
											Description: "HTTP scheme to use for scraping.",
											Type:        "string",
										},
										"scrapeTimeout": {
											Description: "Timeout after which the scrape is ended",
											Type:        "string",
										},
										"scrape_interval": {
											Description: "ScrapeInterval is the same as Interval and has priority over it. one of scrape_interval or interval can be used",
											Type:        "string",
										},
										"targets": {
											Description: "Targets static targets addresses in form of [\"192.122.55.55:9100\",\"some-name:9100\"].",
											Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
											Type:        "array",
										},
										"tlsConfig": {
											Description: "TLSConfig configuration to use when scraping the endpoint",
											Properties: map[string]apiextensionsv1.JSONSchemaProps{
												"ca": {
													Description: "Stuct containing the CA cert to use for the targets.",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"configMap": {
															Description: "ConfigMap containing data to use for the targets.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"key": {
																	Description: "The key to select.",
																	Type:        "string",
																},
																"name": {
																	Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																	Type:        "string",
																},
																"optional": {
																	Description: "Specify whether the ConfigMap or its key must be defined",
																	Type:        "boolean",
																},
															},
															Required: []string{"key"},
															Type:     "object",
															XMapType: P("atomic"),
														},
														"secret": {
															Description: "Secret containing data to use for the targets.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"key": {
																	Description: "The key of the secret to select from.  Must be a valid secret key.",
																	Type:        "string",
																},
																"name": {
																	Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																	Type:        "string",
																},
																"optional": {
																	Description: "Specify whether the Secret or its key must be defined",
																	Type:        "boolean",
																},
															},
															Required: []string{"key"},
															Type:     "object",
															XMapType: P("atomic"),
														},
													},
													Type: "object",
												},
												"caFile": {
													Description: "Path to the CA cert in the container to use for the targets.",
													Type:        "string",
												},
												"cert": {
													Description: "Struct containing the client cert file for the targets.",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"configMap": {
															Description: "ConfigMap containing data to use for the targets.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"key": {
																	Description: "The key to select.",
																	Type:        "string",
																},
																"name": {
																	Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																	Type:        "string",
																},
																"optional": {
																	Description: "Specify whether the ConfigMap or its key must be defined",
																	Type:        "boolean",
																},
															},
															Required: []string{"key"},
															Type:     "object",
															XMapType: P("atomic"),
														},
														"secret": {
															Description: "Secret containing data to use for the targets.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"key": {
																	Description: "The key of the secret to select from.  Must be a valid secret key.",
																	Type:        "string",
																},
																"name": {
																	Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																	Type:        "string",
																},
																"optional": {
																	Description: "Specify whether the Secret or its key must be defined",
																	Type:        "boolean",
																},
															},
															Required: []string{"key"},
															Type:     "object",
															XMapType: P("atomic"),
														},
													},
													Type: "object",
												},
												"certFile": {
													Description: "Path to the client cert file in the container for the targets.",
													Type:        "string",
												},
												"insecureSkipVerify": {
													Description: "Disable target certificate validation.",
													Type:        "boolean",
												},
												"keyFile": {
													Description: "Path to the client key file in the container for the targets.",
													Type:        "string",
												},
												"keySecret": {
													Description: "Secret containing the client key file for the targets.",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"key": {
															Description: "The key of the secret to select from.  Must be a valid secret key.",
															Type:        "string",
														},
														"name": {
															Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
															Type:        "string",
														},
														"optional": {
															Description: "Specify whether the Secret or its key must be defined",
															Type:        "boolean",
														},
													},
													Required: []string{"key"},
													Type:     "object",
													XMapType: P("atomic"),
												},
												"serverName": {
													Description: "Used to verify the hostname for the targets.",
													Type:        "string",
												},
											},
											Type: "object",
										},
										"vm_scrape_params": {
											Description: "VMScrapeParams defines VictoriaMetrics specific scrape parametrs",
											Properties: map[string]apiextensionsv1.JSONSchemaProps{
												"disable_compression": {Type: "boolean"},
												"disable_keep_alive":  {Type: "boolean"},
												"headers": {
													Description: "Headers allows sending custom headers to scrape targets must be in of semicolon separated header with it's value eg: headerName: headerValue vmagent supports since 1.79.0 version",
													Items:       &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &apiextensionsv1.JSONSchemaProps{Type: "string"}},
													Type:        "array",
												},
												"metric_relabel_debug": {Type: "boolean"},
												"no_stale_markers":     {Type: "boolean"},
												"proxy_client_config": {
													Description: "ProxyClientConfig configures proxy auth settings for scraping See feature description https://docs.victoriametrics.com/vmagent.html#scraping-targets-via-a-proxy",
													Properties: map[string]apiextensionsv1.JSONSchemaProps{
														"basic_auth": {
															Description: "BasicAuth allow an endpoint to authenticate over basic authentication",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"password": {
																	Description: "The secret in the service scrape namespace that contains the password for authentication. It must be at them same namespace as CRD",
																	Properties: map[string]apiextensionsv1.JSONSchemaProps{
																		"key": {
																			Description: "The key of the secret to select from.  Must be a valid secret key.",
																			Type:        "string",
																		},
																		"name": {
																			Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																			Type:        "string",
																		},
																		"optional": {
																			Description: "Specify whether the Secret or its key must be defined",
																			Type:        "boolean",
																		},
																	},
																	Required: []string{"key"},
																	Type:     "object",
																	XMapType: P("atomic"),
																},
																"password_file": {
																	Description: "PasswordFile defines path to password file at disk",
																	Type:        "string",
																},
																"username": {
																	Description: "The secret in the service scrape namespace that contains the username for authentication. It must be at them same namespace as CRD",
																	Properties: map[string]apiextensionsv1.JSONSchemaProps{
																		"key": {
																			Description: "The key of the secret to select from.  Must be a valid secret key.",
																			Type:        "string",
																		},
																		"name": {
																			Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																			Type:        "string",
																		},
																		"optional": {
																			Description: "Specify whether the Secret or its key must be defined",
																			Type:        "boolean",
																		},
																	},
																	Required: []string{"key"},
																	Type:     "object",
																	XMapType: P("atomic"),
																},
															},
															Type: "object",
														},
														"bearer_token": {
															Description: "SecretKeySelector selects a key of a Secret.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"key": {
																	Description: "The key of the secret to select from.  Must be a valid secret key.",
																	Type:        "string",
																},
																"name": {
																	Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																	Type:        "string",
																},
																"optional": {
																	Description: "Specify whether the Secret or its key must be defined",
																	Type:        "boolean",
																},
															},
															Required: []string{"key"},
															Type:     "object",
															XMapType: P("atomic"),
														},
														"bearer_token_file": {Type: "string"},
														"tls_config": {
															Description: "TLSConfig specifies TLSConfig configuration parameters.",
															Properties: map[string]apiextensionsv1.JSONSchemaProps{
																"ca": {
																	Description: "Stuct containing the CA cert to use for the targets.",
																	Properties: map[string]apiextensionsv1.JSONSchemaProps{
																		"configMap": {
																			Description: "ConfigMap containing data to use for the targets.",
																			Properties: map[string]apiextensionsv1.JSONSchemaProps{
																				"key": {
																					Description: "The key to select.",
																					Type:        "string",
																				},
																				"name": {
																					Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																					Type:        "string",
																				},
																				"optional": {
																					Description: "Specify whether the ConfigMap or its key must be defined",
																					Type:        "boolean",
																				},
																			},
																			Required: []string{"key"},
																			Type:     "object",
																			XMapType: P("atomic"),
																		},
																		"secret": {
																			Description: "Secret containing data to use for the targets.",
																			Properties: map[string]apiextensionsv1.JSONSchemaProps{
																				"key": {
																					Description: "The key of the secret to select from.  Must be a valid secret key.",
																					Type:        "string",
																				},
																				"name": {
																					Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																					Type:        "string",
																				},
																				"optional": {
																					Description: "Specify whether the Secret or its key must be defined",
																					Type:        "boolean",
																				},
																			},
																			Required: []string{"key"},
																			Type:     "object",
																			XMapType: P("atomic"),
																		},
																	},
																	Type: "object",
																},
																"caFile": {
																	Description: "Path to the CA cert in the container to use for the targets.",
																	Type:        "string",
																},
																"cert": {
																	Description: "Struct containing the client cert file for the targets.",
																	Properties: map[string]apiextensionsv1.JSONSchemaProps{
																		"configMap": {
																			Description: "ConfigMap containing data to use for the targets.",
																			Properties: map[string]apiextensionsv1.JSONSchemaProps{
																				"key": {
																					Description: "The key to select.",
																					Type:        "string",
																				},
																				"name": {
																					Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																					Type:        "string",
																				},
																				"optional": {
																					Description: "Specify whether the ConfigMap or its key must be defined",
																					Type:        "boolean",
																				},
																			},
																			Required: []string{"key"},
																			Type:     "object",
																			XMapType: P("atomic"),
																		},
																		"secret": {
																			Description: "Secret containing data to use for the targets.",
																			Properties: map[string]apiextensionsv1.JSONSchemaProps{
																				"key": {
																					Description: "The key of the secret to select from.  Must be a valid secret key.",
																					Type:        "string",
																				},
																				"name": {
																					Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																					Type:        "string",
																				},
																				"optional": {
																					Description: "Specify whether the Secret or its key must be defined",
																					Type:        "boolean",
																				},
																			},
																			Required: []string{"key"},
																			Type:     "object",
																			XMapType: P("atomic"),
																		},
																	},
																	Type: "object",
																},
																"certFile": {
																	Description: "Path to the client cert file in the container for the targets.",
																	Type:        "string",
																},
																"insecureSkipVerify": {
																	Description: "Disable target certificate validation.",
																	Type:        "boolean",
																},
																"keyFile": {
																	Description: "Path to the client key file in the container for the targets.",
																	Type:        "string",
																},
																"keySecret": {
																	Description: "Secret containing the client key file for the targets.",
																	Properties: map[string]apiextensionsv1.JSONSchemaProps{
																		"key": {
																			Description: "The key of the secret to select from.  Must be a valid secret key.",
																			Type:        "string",
																		},
																		"name": {
																			Description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
																			Type:        "string",
																		},
																		"optional": {
																			Description: "Specify whether the Secret or its key must be defined",
																			Type:        "boolean",
																		},
																	},
																	Required: []string{"key"},
																	Type:     "object",
																	XMapType: P("atomic"),
																},
																"serverName": {
																	Description: "Used to verify the hostname for the targets.",
																	Type:        "string",
																},
															},
															Type: "object",
														},
													},
													Type: "object",
												},
												"relabel_debug":         {Type: "boolean"},
												"scrape_align_interval": {Type: "string"},
												"scrape_offset":         {Type: "string"},
												"stream_parse":          {Type: "boolean"},
											},
											Type: "object",
										},
									},
									Required: []string{"targets"},
									Type:     "object",
								}},
								Type: "array",
							},
						},
						Required: []string{"targetEndpoints"},
						Type:     "object",
					},
					"status": {
						Description: "VMStaticScrapeStatus defines the observed state of VMStaticScrape",
						Type:        "object",
					},
				},
				Type: "object",
			}},
			Served:       true,
			Storage:      true,
			Subresources: &apiextensionsv1.CustomResourceSubresources{},
		}},
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "apiextensions.k8s.io/v1",
		Kind:       "CustomResourceDefinition",
	},
}
