// Copyright (c) 2023 Volvo Car Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package metricsserver

import (
	v1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var ServiceMonitor = &v1.ServiceMonitor{
	ObjectMeta: metav1.ObjectMeta{
		Labels: map[string]string{
			"app.kubernetes.io/instance":   "metrics-server",
			"app.kubernetes.io/managed-by": "Helm",
			"app.kubernetes.io/name":       "metrics-server",
			"app.kubernetes.io/version":    "0.6.3",
			"helm.sh/chart":                "metrics-server-3.10.0",
		},
		Name:      "metrics-server",
		Namespace: namespace,
	},
	Spec: v1.ServiceMonitorSpec{
		Endpoints: []v1.Endpoint{
			{
				Interval:      v1.Duration("1m"),
				Path:          "/metrics",
				Port:          "https",
				Scheme:        "https",
				ScrapeTimeout: v1.Duration("10s"),
				TLSConfig:     &v1.TLSConfig{SafeTLSConfig: v1.SafeTLSConfig{InsecureSkipVerify: true}},
			},
		},
		JobLabel:          "metrics-server",
		NamespaceSelector: v1.NamespaceSelector{MatchNames: []string{namespace}},
		Selector: metav1.LabelSelector{
			MatchLabels: map[string]string{
				"app.kubernetes.io/instance": "metrics-server",
				"app.kubernetes.io/name":     "metrics-server",
			},
		},
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "monitoring.coreos.com/v1",
		Kind:       "ServiceMonitor",
	},
}
