name: pr

on:
  pull_request:

concurrency:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
  group: ${{ github.workflow }}-${{ github.ref }} # To only cancel in-progress runs of the same workflow
  cancel-in-progress: true

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test:
    permissions:
      contents: read # for actions/checkout to fetch code
      # pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0
        with:
          fetch-depth: 1

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "./go.mod"
          check-latest: true
          cache-dependency-path: ./go.mod

      # Dependency for terra-related tests.
      - uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1.0.5
        with:
          tofu_version: 1.6.2
          # This is necessary. Otherwise the exitcode when calling tofu will be
          # "wrapped" and not returned to lingon. *facepalm*
          tofu_wrapper: false

      - name: run CI
        run: go run ./cmd/tools/ci/ -pr -nodiff
